import type { Schemas } from "@/api/client";

// Captured synthetic backend projection; current capability and historical result remain independent.
export const technicalCapability = {
  version: "daily_derived_v1",
  source_mode: "historical_retrospective",
  fields: [
    {
      column: "open",
      name_zh: "开盘价",
      description_zh: "日线记录的开盘价。",
    },
    {
      column: "high",
      name_zh: "最高价",
      description_zh: "日线记录的最高价。",
    },
    {
      column: "low",
      name_zh: "最低价",
      description_zh: "日线记录的最低价。",
    },
    {
      column: "close",
      name_zh: "收盘价",
      description_zh: "日线记录的收盘价。",
    },
    {
      column: "vol",
      name_zh: "成交量",
      description_zh: "日线记录的成交量。",
    },
    {
      column: "amount",
      name_zh: "成交额",
      description_zh: "日线记录的成交额。",
    },
    {
      column: "circ_mv",
      name_zh: "流通市值",
      description_zh: "当日流通市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "kdj_d",
      name_zh: "KDJ D",
      description_zh: "从首个有效历史观察推导；历史断裂不重置。",
      unit: "indicator",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "kdj_j",
      name_zh: "KDJ J",
      description_zh: "从首个有效历史观察推导；历史断裂不重置，KDJ J保留原值。",
      unit: "indicator",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "kdj_k",
      name_zh: "KDJ K",
      description_zh: "从首个有效历史观察推导；历史断裂不重置。",
      unit: "indicator",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "ma10",
      name_zh: "10日均线",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "ma20",
      name_zh: "20日均线",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "ma5",
      name_zh: "5日均线",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "ma60",
      name_zh: "60日均线",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "macd",
      name_zh: "MACD DIF",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "macd_hist",
      name_zh: "MACD柱差值",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "macd_signal",
      name_zh: "MACD信号线",
      description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
      unit: "session_price",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "rsi14",
      name_zh: "14日RSI",
      description_zh: "从首个有效历史观察推导；历史断裂不重置。",
      unit: "indicator",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "rsi6",
      name_zh: "6日RSI",
      description_zh: "从首个有效历史观察推导；历史断裂不重置。",
      unit: "indicator",
      value_semantics: "history_derived",
      tracking_supported: true,
    },
    {
      column: "total_mv",
      name_zh: "总市值",
      description_zh: "当日总市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "turnover_rate",
      name_zh: "换手率",
      description_zh: "百分数原值；0.5387表示0.5387%，不乘100。",
      unit: "percent",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "volume_ratio",
      name_zh: "量比",
      description_zh: "供应方当日量比原值，不由日线重算。",
      unit: "ratio",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
  ],
  runnable_operators: [
    "+",
    "-",
    "*",
    "/",
    "<",
    "<=",
    ">",
    ">=",
    "ts_mean",
    "ts_std",
    "ts_delta",
    "ts_rank",
    "ref",
    "ts_corr",
    "cs_rank",
    "cs_zscore",
    "cs_winsorize",
  ],
  unavailable_operators: [
    {
      name: "industry_neutralize",
      reason_zh: "历史来源缺少可核验的行业归属。",
    },
    {
      name: "size_neutralize",
      reason_zh: "历史来源缺少可核验的市值数据。",
    },
  ],
  can_save: true,
  coverage_note_zh: "字段和算子支持不代表历史数据已覆盖。",
} satisfies Schemas["FactorCapabilitiesData"];

export const technicalResearch = {
  schema_version: 2,
  basis_label: "历史回溯研究；分组曲线不含撮合与交易费用。",
  pool_label: "全市场（沪深非 ST）",
  return_price_basis: "forward_adjusted",
  holding_sessions: 1,
  summary_status: "evaluated",
  ic_summary: {
    normal_ic: {
      status: "ok",
      source_day_count: 3,
      valid_day_count: 3,
      insufficient_day_count: 0,
      zero_variance_day_count: 0,
      mean: 1.0,
      sample_std: 6.409875621278547e-17,
      ir: 1.5600926743107922e16,
      positive_rate: 1.0,
      strong_signal_rate: 1.0,
      t_value: 2.7021597764222972e16,
      p_value: 1.3695501826753565e-33,
      skewness: 0.7071067811865475,
      excess_kurtosis: -1.5000000000000007,
    },
    rank_ic: {
      status: "zero_variance",
      source_day_count: 3,
      valid_day_count: 3,
      insufficient_day_count: 0,
      zero_variance_day_count: 0,
      mean: 1.0,
      sample_std: 0.0,
      ir: null,
      positive_rate: 1.0,
      strong_signal_rate: 1.0,
      t_value: null,
      p_value: null,
      skewness: null,
      excess_kurtosis: null,
    },
  },
  ic_points: [
    {
      decision_date: "2026-09-01",
      normal_ic: {
        status: "ok",
        value: 0.9999999999999999,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      rank_ic: {
        status: "ok",
        value: 1.0,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      normal_ic_cumulative_sum: 0.9999999999999999,
      rank_ic_cumulative_sum: 1.0,
    },
    {
      decision_date: "2026-09-02",
      normal_ic: {
        status: "ok",
        value: 0.9999999999999999,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      rank_ic: {
        status: "ok",
        value: 1.0,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      normal_ic_cumulative_sum: 1.9999999999999998,
      rank_ic_cumulative_sum: 2.0,
    },
    {
      decision_date: "2026-09-03",
      normal_ic: {
        status: "ok",
        value: 1.0,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      rank_ic: {
        status: "ok",
        value: 1.0,
        source_sample_count: 9,
        effective_sample_count: 9,
      },
      normal_ic_cumulative_sum: 3.0,
      rank_ic_cumulative_sum: 3.0,
    },
  ],
  decay_periods: [
    {
      lag: 1,
      status: "evaluated",
      source_day_count: 3,
      valid_pair_count: 27,
      ic_summary: {
        normal_ic: {
          status: "ok",
          source_day_count: 3,
          valid_day_count: 3,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 1.0,
          sample_std: 6.409875621278547e-17,
          ir: 1.5600926743107922e16,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: 2.7021597764222972e16,
          p_value: 1.3695501826753565e-33,
          skewness: 0.7071067811865475,
          excess_kurtosis: -1.5000000000000007,
        },
        rank_ic: {
          status: "zero_variance",
          source_day_count: 3,
          valid_day_count: 3,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 1.0,
          sample_std: 0.0,
          ir: null,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: null,
          p_value: null,
          skewness: null,
          excess_kurtosis: null,
        },
      },
    },
    {
      lag: 2,
      status: "evaluated",
      source_day_count: 2,
      valid_pair_count: 18,
      ic_summary: {
        normal_ic: {
          status: "zero_variance",
          source_day_count: 2,
          valid_day_count: 2,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 0.9999999999999999,
          sample_std: 0.0,
          ir: null,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: null,
          p_value: null,
          skewness: null,
          excess_kurtosis: null,
        },
        rank_ic: {
          status: "zero_variance",
          source_day_count: 2,
          valid_day_count: 2,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 1.0,
          sample_std: 0.0,
          ir: null,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: null,
          p_value: null,
          skewness: null,
          excess_kurtosis: null,
        },
      },
    },
    {
      lag: 3,
      status: "evaluated",
      source_day_count: 1,
      valid_pair_count: 9,
      ic_summary: {
        normal_ic: {
          status: "insufficient_samples",
          source_day_count: 1,
          valid_day_count: 1,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 0.9999999999999999,
          sample_std: null,
          ir: null,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: null,
          p_value: null,
          skewness: null,
          excess_kurtosis: null,
        },
        rank_ic: {
          status: "insufficient_samples",
          source_day_count: 1,
          valid_day_count: 1,
          insufficient_day_count: 0,
          zero_variance_day_count: 0,
          mean: 1.0,
          sample_std: null,
          ir: null,
          positive_rate: 1.0,
          strong_signal_rate: 1.0,
          t_value: null,
          p_value: null,
          skewness: null,
          excess_kurtosis: null,
        },
      },
    },
    {
      lag: 4,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 5,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 6,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 7,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 8,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 9,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
    {
      lag: 10,
      status: "no_target_period",
      source_day_count: 0,
      valid_pair_count: 0,
      ic_summary: null,
    },
  ],
  portfolio_status: "available_partial",
  portfolio_days: [
    {
      decision_date: "2026-09-01",
      groupings: [
        {
          group_count: 3,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 3,
              period_return: -0.14536340852130325,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.14536340852130325,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 5,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 2,
              period_return: -0.21804511278195488,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 4,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 5,
              member_count: 1,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.21804511278195488,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 10,
          status: "insufficient_samples",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [],
          long_short_return: null,
          long_short_cumulative_spread: null,
        },
      ],
    },
    {
      decision_date: "2026-09-02",
      groupings: [
        {
          group_count: 3,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 3,
              period_return: -0.1486611265004617,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.1486611265004617,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 5,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 2,
              period_return: -0.22299168975069256,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 4,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 5,
              member_count: 1,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.22299168975069256,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 10,
          status: "insufficient_samples",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [],
          long_short_return: null,
          long_short_cumulative_spread: null,
        },
      ],
    },
    {
      decision_date: "2026-09-03",
      groupings: [
        {
          group_count: 3,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 3,
              period_return: -0.15184513006654568,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 3,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.15184513006654568,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 5,
          status: "ok",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [
            {
              group_number: 1,
              member_count: 2,
              period_return: -0.22776769509981853,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 2,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 3,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 4,
              member_count: 2,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
            {
              group_number: 5,
              member_count: 1,
              period_return: 0.0,
              cumulative_return: null,
              target_weight_turnover: null,
            },
          ],
          long_short_return: 0.22776769509981853,
          long_short_cumulative_spread: null,
        },
        {
          group_count: 10,
          status: "insufficient_samples",
          cumulative_status: "gap",
          source_sample_count: 9,
          effective_sample_count: 9,
          groups: [],
          long_short_return: null,
          long_short_cumulative_spread: null,
        },
      ],
    },
  ],
  coverage_days: [
    {
      decision_date: "2026-09-01",
      status: "partial",
      coverage: {
        expected_count: 12,
        valid_count: 9,
        factor_missing_count: 3,
        return_missing_count: 2,
        factor_missing_by_reason: [
          {
            reason: "missing_observation",
            count: 1,
          },
          {
            reason: "missing_value",
            count: 2,
          },
        ],
        return_missing_by_reason: [
          {
            reason: "missing_price",
            count: 1,
          },
          {
            reason: "source_unavailable",
            count: 1,
          },
        ],
      },
    },
    {
      decision_date: "2026-09-02",
      status: "partial",
      coverage: {
        expected_count: 12,
        valid_count: 9,
        factor_missing_count: 3,
        return_missing_count: 2,
        factor_missing_by_reason: [
          {
            reason: "missing_observation",
            count: 1,
          },
          {
            reason: "missing_value",
            count: 2,
          },
        ],
        return_missing_by_reason: [
          {
            reason: "missing_price",
            count: 1,
          },
          {
            reason: "source_unavailable",
            count: 1,
          },
        ],
      },
    },
    {
      decision_date: "2026-09-03",
      status: "partial",
      coverage: {
        expected_count: 12,
        valid_count: 9,
        factor_missing_count: 3,
        return_missing_count: 2,
        factor_missing_by_reason: [
          {
            reason: "missing_observation",
            count: 1,
          },
          {
            reason: "missing_value",
            count: 2,
          },
        ],
        return_missing_by_reason: [
          {
            reason: "missing_price",
            count: 1,
          },
          {
            reason: "source_unavailable",
            count: 1,
          },
        ],
      },
    },
  ],
  neutralization: "none",
  neutralization_label: "无",
  context_basis_label: null,
  context_note: null,
  mad_multiple: null,
  extended_statistics: {
    ic_method: "rank",
    industry_status: "unavailable",
    industry_reason: "缺少可核验的行业来源，未生成行业 IC。",
    industry_summaries: [],
    industry_coverage_days: [],
    autocorrelation_points: [
      {
        trade_date: "2026-09-01",
        previous_trade_date: null,
        common_count: 0,
        status: "first_period",
        value: null,
      },
      {
        trade_date: "2026-09-02",
        previous_trade_date: "2026-09-01",
        common_count: 9,
        status: "ok",
        value: 1.0,
      },
      {
        trade_date: "2026-09-03",
        previous_trade_date: "2026-09-02",
        common_count: 9,
        status: "ok",
        value: 1.0,
      },
    ],
  },
  daily_features: {
    source_sha256: "a788adaa05f172c2a9803ed12d5e87bc9034b385031dd5e48cd3b5cf8fdea8ce",
    prepared_source_sha256: "883ef30ebdc8990b2bb43ff8170c00ebccf8e90a9cda9bf95a7b6fcaaac251f2",
    prepared_snapshot_id: "cc1ac2671156d49ebebbdb04492c802c9c94cf9909566cbab930c56e00cc414d",
    prepared_binding_hash: "000a79808847bcb15da7eaf298e68a8f4ddedde22664dbb49021f6290cc017ab",
    scope_content_hash: "92eff7a26ca5c9f1f63a0cdda5164fdead989ce0e4ec66d19b289fdcf5f40369",
    code_commit: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    fields: [
      {
        column: "ma5",
        table: "daily_indicator",
        name_zh: "5日均线",
        unit: "session_price",
        description_zh: "从首个有效历史观察推导，按观察日复权因子计算、当日因子还原价格。",
        value_semantics: "history_derived",
      },
      {
        column: "turnover_rate",
        table: "daily_basic",
        name_zh: "换手率",
        unit: "percent",
        description_zh: "百分数原值；0.5387表示0.5387%，不乘100。",
      },
    ],
    source_mode: "historical_retrospective",
    value_semantics: "history_derived",
    price_basis: "observation_factor_then_output_session_scale",
    recursive_initialization: "first_valid_observation_no_restart",
    technical_history: {
      policy: {
        algorithm_version: "rquant-ta-0.11.0-v1",
        implementation_sha256: "44aa148e01f535666ab8b3abb604fc41e47f38e5303e9adc2f6de2ea2f7d58e3",
        price_basis: "observation_factor_then_output_session_scale",
        initialization: "first_valid_observation_no_restart",
        bad_observation: "blocks_reliable_suffix",
        absent_bar: "no_synthetic_observation",
      },
      source_history_start: "2026-07-01",
      initialized_codes: 10,
      uninitialized_codes: 2,
      broken_codes: 1,
      leading_invalid_observations: 85,
    },
  },
  daily_feature_coverage_days: [
    {
      trade_date: "2026-09-01",
      panel_date: "2026-08-31",
      computation_stock_count: 12,
      counts: [
        {
          column: "ma5",
          valid: 9,
          missing: 1,
          null: 2,
          non_finite: 0,
          reasons: [
            {
              reason: "history_break",
              count: 1,
            },
            {
              reason: "no_initialization",
              count: 2,
            },
          ],
        },
        {
          column: "turnover_rate",
          valid: 12,
          missing: 0,
          null: 0,
          non_finite: 0,
        },
      ],
    },
    {
      trade_date: "2026-09-02",
      panel_date: "2026-09-01",
      computation_stock_count: 12,
      counts: [
        {
          column: "ma5",
          valid: 9,
          missing: 1,
          null: 2,
          non_finite: 0,
          reasons: [
            {
              reason: "history_break",
              count: 1,
            },
            {
              reason: "no_initialization",
              count: 2,
            },
          ],
        },
        {
          column: "turnover_rate",
          valid: 12,
          missing: 0,
          null: 0,
          non_finite: 0,
        },
      ],
    },
    {
      trade_date: "2026-09-03",
      panel_date: "2026-09-02",
      computation_stock_count: 12,
      counts: [
        {
          column: "ma5",
          valid: 9,
          missing: 1,
          null: 2,
          non_finite: 0,
          reasons: [
            {
              reason: "history_break",
              count: 1,
            },
            {
              reason: "no_initialization",
              count: 2,
            },
          ],
        },
        {
          column: "turnover_rate",
          valid: 12,
          missing: 0,
          null: 0,
          non_finite: 0,
        },
      ],
    },
  ],
} satisfies Schemas["FactorStreamResearchDisplay"];
