import type { Schemas } from "@/api/client";
import { trackedFactor } from "./factorTracking.fixture";

// Captured trusted capability from the frozen backend; no field metadata is rebuilt here.
export const storedTrackingCapability = {
  version: "daily_stored_v1",
  source_mode: "historical_retrospective",
  fields: [
    {
      column: "open",
      name_zh: "开盘价",
      description_zh: "日线记录的开盘价。",
    },
    {
      column: "high",
      name_zh: "最高价",
      description_zh: "日线记录的最高价。",
    },
    {
      column: "low",
      name_zh: "最低价",
      description_zh: "日线记录的最低价。",
    },
    {
      column: "close",
      name_zh: "收盘价",
      description_zh: "日线记录的收盘价。",
    },
    {
      column: "vol",
      name_zh: "成交量",
      description_zh: "日线记录的成交量。",
    },
    {
      column: "amount",
      name_zh: "成交额",
      description_zh: "日线记录的成交额。",
    },
    {
      column: "circ_mv",
      name_zh: "流通市值",
      description_zh: "当日流通市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "kdj_d",
      name_zh: "KDJ D",
      description_zh: "已存KDJ D点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "kdj_j",
      name_zh: "KDJ J",
      description_zh: "已存KDJ J点值，初始化未核验；保留原值，不裁到0–100。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "kdj_k",
      name_zh: "KDJ K",
      description_zh: "已存KDJ K点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "ma10",
      name_zh: "10日均线",
      description_zh: "已存10日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "ma20",
      name_zh: "20日均线",
      description_zh: "已存20日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "ma5",
      name_zh: "5日均线",
      description_zh: "已存5日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "ma60",
      name_zh: "60日均线",
      description_zh: "已存60日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "macd",
      name_zh: "MACD DIF",
      description_zh: "已存MACD DIF，价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "macd_hist",
      name_zh: "MACD柱差值",
      description_zh: "已存DIF−DEA，不另乘2；价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "macd_signal",
      name_zh: "MACD信号线",
      description_zh: "已存MACD信号线，价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "rsi14",
      name_zh: "14日RSI",
      description_zh: "已存14日RSI点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "rsi6",
      name_zh: "6日RSI",
      description_zh: "已存6日RSI点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "total_mv",
      name_zh: "总市值",
      description_zh: "当日总市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "turnover_rate",
      name_zh: "换手率",
      description_zh: "百分数原值；0.5387表示0.5387%，不乘100。",
      unit: "percent",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
    {
      column: "volume_ratio",
      name_zh: "量比",
      description_zh: "供应方当日量比原值，不由日线重算。",
      unit: "ratio",
      value_semantics: "stored_not_recomputed",
      tracking_supported: true,
    },
  ],
  runnable_operators: [
    "+",
    "-",
    "*",
    "/",
    "<",
    "<=",
    ">",
    ">=",
    "ts_mean",
    "ts_std",
    "ts_delta",
    "ts_rank",
    "ref",
    "ts_corr",
    "cs_rank",
    "cs_zscore",
    "cs_winsorize",
  ],
  unavailable_operators: [
    {
      name: "industry_neutralize",
      reason_zh: "历史来源缺少可核验的行业归属。",
    },
    {
      name: "size_neutralize",
      reason_zh: "历史来源缺少可核验的市值数据。",
    },
  ],
  can_save: true,
  coverage_note_zh: "字段和算子支持不代表历史数据已覆盖。",
} satisfies Schemas["FactorCapabilitiesData"];

export const storedTrackingFactor: Schemas["FactorDefinitionItem"] = {
  ...trackedFactor,
  name_zh: "库存价量",
  expression: "turnover_rate + ref(ma20, 1)",
  dependency_columns: ["ma20", "turnover_rate"],
};
