import type { Schemas } from "@/api/client";
import { diagnosticResearch } from "./factorDiagnostics.fixture";

// Independent unavailable-tracking fixture; current trusted support is captured in factorStoredTracking.fixture.
// Stored-field metadata and synthetic research below retain their original source facts.
export const dailyCapability = {
  version: "daily_stored_v1",
  source_mode: "historical_retrospective",
  fields: [
    {
      column: "open",
      name_zh: "开盘价",
      description_zh: "日线记录的开盘价。",
    },
    {
      column: "high",
      name_zh: "最高价",
      description_zh: "日线记录的最高价。",
    },
    {
      column: "low",
      name_zh: "最低价",
      description_zh: "日线记录的最低价。",
    },
    {
      column: "close",
      name_zh: "收盘价",
      description_zh: "日线记录的收盘价。",
    },
    {
      column: "vol",
      name_zh: "成交量",
      description_zh: "日线记录的成交量。",
    },
    {
      column: "amount",
      name_zh: "成交额",
      description_zh: "日线记录的成交额。",
    },
    {
      column: "circ_mv",
      name_zh: "流通市值",
      description_zh: "当日流通市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "kdj_d",
      name_zh: "KDJ D",
      description_zh: "已存KDJ D点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "kdj_j",
      name_zh: "KDJ J",
      description_zh: "已存KDJ J点值，初始化未核验；保留原值，不裁到0–100。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "kdj_k",
      name_zh: "KDJ K",
      description_zh: "已存KDJ K点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "ma10",
      name_zh: "10日均线",
      description_zh: "已存10日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "ma20",
      name_zh: "20日均线",
      description_zh: "已存20日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "ma5",
      name_zh: "5日均线",
      description_zh: "已存5日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "ma60",
      name_zh: "60日均线",
      description_zh: "已存60日均线，价格基准未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "macd",
      name_zh: "MACD DIF",
      description_zh: "已存MACD DIF，价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "macd_hist",
      name_zh: "MACD柱差值",
      description_zh: "已存DIF−DEA，不另乘2；价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "macd_signal",
      name_zh: "MACD信号线",
      description_zh: "已存MACD信号线，价格基准及初始化未核验。",
      unit: "stored_price",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "rsi14",
      name_zh: "14日RSI",
      description_zh: "已存14日RSI点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "rsi6",
      name_zh: "6日RSI",
      description_zh: "已存6日RSI点值，初始化未核验。",
      unit: "indicator",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "total_mv",
      name_zh: "总市值",
      description_zh: "当日总市值原值，单位万元。",
      unit: "CNY_10000",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "turnover_rate",
      name_zh: "换手率",
      description_zh: "百分数原值；0.5387表示0.5387%，不乘100。",
      unit: "percent",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
    {
      column: "volume_ratio",
      name_zh: "量比",
      description_zh: "供应方当日量比原值，不由日线重算。",
      unit: "ratio",
      value_semantics: "stored_not_recomputed",
      tracking_supported: false,
      tracking_unavailable_reason_zh: "库存日线字段暂不支持持续跟踪。",
    },
  ],
  runnable_operators: [
    "+",
    "-",
    "*",
    "/",
    "<",
    "<=",
    ">",
    ">=",
    "ts_mean",
    "ts_std",
    "ts_delta",
    "ts_rank",
    "ref",
    "ts_corr",
    "cs_rank",
    "cs_zscore",
    "cs_winsorize",
  ],
  unavailable_operators: [
    {
      name: "industry_neutralize",
      reason_zh: "历史来源缺少可核验的行业归属。",
    },
    {
      name: "size_neutralize",
      reason_zh: "历史来源缺少可核验的市值数据。",
    },
  ],
  can_save: true,
  coverage_note_zh: "字段和算子支持不代表历史数据已覆盖。",
} satisfies Schemas["FactorCapabilitiesData"];

export const dailyStoredFields = [
  {
    column: "circ_mv",
    table: "daily_basic",
    name_zh: "流通市值",
    unit: "CNY_10000",
    description_zh: "当日流通市值原值，单位万元。",
  },
  {
    column: "kdj_d",
    table: "daily_indicator",
    name_zh: "KDJ D",
    unit: "indicator",
    description_zh: "已存KDJ D点值，初始化未核验。",
  },
  {
    column: "kdj_j",
    table: "daily_indicator",
    name_zh: "KDJ J",
    unit: "indicator",
    description_zh: "已存KDJ J点值，初始化未核验；保留原值，不裁到0–100。",
  },
  {
    column: "kdj_k",
    table: "daily_indicator",
    name_zh: "KDJ K",
    unit: "indicator",
    description_zh: "已存KDJ K点值，初始化未核验。",
  },
  {
    column: "ma10",
    table: "daily_indicator",
    name_zh: "10日均线",
    unit: "stored_price",
    description_zh: "已存10日均线，价格基准未核验。",
  },
  {
    column: "ma20",
    table: "daily_indicator",
    name_zh: "20日均线",
    unit: "stored_price",
    description_zh: "已存20日均线，价格基准未核验。",
  },
  {
    column: "ma5",
    table: "daily_indicator",
    name_zh: "5日均线",
    unit: "stored_price",
    description_zh: "已存5日均线，价格基准未核验。",
  },
  {
    column: "ma60",
    table: "daily_indicator",
    name_zh: "60日均线",
    unit: "stored_price",
    description_zh: "已存60日均线，价格基准未核验。",
  },
  {
    column: "macd",
    table: "daily_indicator",
    name_zh: "MACD DIF",
    unit: "stored_price",
    description_zh: "已存MACD DIF，价格基准及初始化未核验。",
  },
  {
    column: "macd_hist",
    table: "daily_indicator",
    name_zh: "MACD柱差值",
    unit: "stored_price",
    description_zh: "已存DIF−DEA，不另乘2；价格基准及初始化未核验。",
  },
  {
    column: "macd_signal",
    table: "daily_indicator",
    name_zh: "MACD信号线",
    unit: "stored_price",
    description_zh: "已存MACD信号线，价格基准及初始化未核验。",
  },
  {
    column: "rsi14",
    table: "daily_indicator",
    name_zh: "14日RSI",
    unit: "indicator",
    description_zh: "已存14日RSI点值，初始化未核验。",
  },
  {
    column: "rsi6",
    table: "daily_indicator",
    name_zh: "6日RSI",
    unit: "indicator",
    description_zh: "已存6日RSI点值，初始化未核验。",
  },
  {
    column: "total_mv",
    table: "daily_basic",
    name_zh: "总市值",
    unit: "CNY_10000",
    description_zh: "当日总市值原值，单位万元。",
  },
  {
    column: "turnover_rate",
    table: "daily_basic",
    name_zh: "换手率",
    unit: "percent",
    description_zh: "百分数原值；0.5387表示0.5387%，不乘100。",
  },
  {
    column: "volume_ratio",
    table: "daily_basic",
    name_zh: "量比",
    unit: "ratio",
    description_zh: "供应方当日量比原值，不由日线重算。",
  },
] satisfies Schemas["FactorDailyStoredField"][];

export const dailyResearch: Schemas["FactorStreamResearchDisplay"] = {
  ...diagnosticResearch,
  daily_features: {
    source_sha256: "2".repeat(64),
    prepared_source_sha256: "3".repeat(64),
    prepared_snapshot_id: "synthetic-daily-fields",
    prepared_binding_hash: "4".repeat(64),
    scope_content_hash: "5".repeat(64),
    code_commit: "6".repeat(40),
    source_mode: "historical_retrospective",
    value_semantics: "stored_not_recomputed",
    price_basis: "unverified",
    recursive_initialization: "unverified",
    fields: dailyStoredFields.filter(
      (field) => field.column === "ma20" || field.column === "turnover_rate",
    ),
  },
  daily_feature_coverage_days: [
    {
      trade_date: "2026-09-22",
      panel_date: "2026-09-21",
      computation_stock_count: 8,
      counts: [
        { column: "ma20", valid: 5, missing: 1, null: 1, non_finite: 1 },
        { column: "turnover_rate", valid: 6, missing: 2, null: 0, non_finite: 0 },
      ],
    },
  ],
};
