/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统健康 */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据代、数据集水位与市场阶段 */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 总览 */
        get: operations["get_overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 板块总表 */
        get: operations["get_boards_api_v1_panorama_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/boards/{board_code}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 板块成分 */
        get: operations["get_members_api_v1_panorama_boards__board_code__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 市场脉搏 */
        get: operations["get_pulse_api_v1_panorama_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/stocks/{ts_code}/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 个股日 K */
        get: operations["get_daily_api_v1_panorama_stocks__ts_code__daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/stocks/{ts_code}/intraday": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 个股分时 / 5 日 */
        get: operations["get_intraday_api_v1_panorama_stocks__ts_code__intraday_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/surge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 爆量记录（按日） */
        get: operations["get_surge_api_v1_panorama_surge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama/surge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 爆量记录（跨日搜索） */
        get: operations["search_surge_api_v1_panorama_surge_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screen/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 选股条件目录 */
        get: operations["get_blocks_api_v1_screen_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screen/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 运行选股条件 */
        post: operations["run_screen_api_v1_screen_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索股票 */
        get: operations["search_stocks_api_v1_stocks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ts_code}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 个股概览 */
        get: operations["get_stock_summary_api_v1_stocks__ts_code__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionCount */
        ActionCount: {
            /** Action */
            action: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /** AttentionItem */
        AttentionItem: {
            /** Action */
            action: string;
            /**
             * Level
             * @enum {string}
             */
            level: "crit" | "warn";
            /** Reason */
            reason: string;
            /** Title */
            title: string;
            /** To */
            to: string;
        };
        /** BoardRow */
        BoardRow: {
            /** Amount */
            amount: number | null;
            /** Board Code */
            board_code: string;
            /** Board Name */
            board_name: string;
            /** Broken Count */
            broken_count: number | null;
            /** Leading Stock */
            leading_stock: string | null;
            /** Limit Up Count */
            limit_up_count: number | null;
            /** Limit Up Ratio Pct */
            limit_up_ratio_pct: number | null;
            /** Main Net Amount */
            main_net_amount: number | null;
            /** Main Net Rate */
            main_net_rate: number | null;
            /** Pct Chg Median */
            pct_chg_median: number | null;
            /** Stock Count */
            stock_count: number | null;
        };
        /** BoardsData */
        BoardsData: {
            /** As Of */
            as_of: string | null;
            /** Has Flow */
            has_flow: boolean;
            /** Rows */
            rows: components["schemas"]["BoardRow"][];
            /** System */
            system: string;
            /** Systems */
            systems: string[];
        };
        /** CandidateGroup */
        CandidateGroup: {
            /** As Of */
            as_of: string | null;
            /** Count */
            count: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "screen" | "signals";
        };
        /** CandidateItem */
        CandidateItem: {
            /** Close */
            close: number | null;
            /** Code */
            code: string;
            /** First Seen At */
            first_seen_at: string | null;
            /** Group */
            group: string;
            /** Group Name */
            group_name: string;
            /** Name */
            name: string | null;
            /** Pct Chg */
            pct_chg: number | null;
        };
        /** CandidatesSummary */
        CandidatesSummary: {
            /** Groups */
            groups: components["schemas"]["CandidateGroup"][];
            /** Items */
            items: components["schemas"]["CandidateItem"][];
            /** Total */
            total: number;
        };
        /** DailyBar */
        DailyBar: {
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Ma10 */
            ma10: number | null;
            /** Ma20 */
            ma20: number | null;
            /** Ma5 */
            ma5: number | null;
            /** Open */
            open: number;
            /** Provisional */
            provisional: boolean;
            /** Volume */
            volume: number | null;
        };
        /** DailyData */
        DailyData: {
            /** Bars */
            bars: components["schemas"]["DailyBar"][];
            /** Name */
            name: string | null;
            /** Ts Code */
            ts_code: string;
        };
        /** DatasetWatermarkInfo */
        DatasetWatermarkInfo: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /** Name */
            name: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Reason */
            reason: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "stale" | "degraded" | "unavailable";
            user_status: components["schemas"]["StatusInfo"];
        };
        /** DeliveriesSummary */
        DeliveriesSummary: {
            /** Delivered */
            delivered: number;
            /** Expired */
            expired: number;
            /** Failed */
            failed: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "shadow" | "unknown";
            /** Mode Label */
            mode_label: string;
            /** Mode Note */
            mode_note: string | null;
            /** Sending */
            sending: number;
            /** Total */
            total: number;
        };
        /** Envelope[BoardsData] */
        Envelope_BoardsData_: {
            data: components["schemas"]["BoardsData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[DailyData] */
        Envelope_DailyData_: {
            data: components["schemas"]["DailyData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[HealthData] */
        Envelope_HealthData_: {
            data: components["schemas"]["HealthData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[IntradayData] */
        Envelope_IntradayData_: {
            data: components["schemas"]["IntradayData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[MembersData] */
        Envelope_MembersData_: {
            data: components["schemas"]["MembersData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[MetaData] */
        Envelope_MetaData_: {
            data: components["schemas"]["MetaData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[OverviewData] */
        Envelope_OverviewData_: {
            data: components["schemas"]["OverviewData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PulseData] */
        Envelope_PulseData_: {
            data: components["schemas"]["PulseData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[ScreenCatalogData] */
        Envelope_ScreenCatalogData_: {
            data: components["schemas"]["ScreenCatalogData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[ScreenRunData] */
        Envelope_ScreenRunData_: {
            data: components["schemas"]["ScreenRunData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[StockSearchData] */
        Envelope_StockSearchData_: {
            data: components["schemas"]["StockSearchData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[StockSummaryData] */
        Envelope_StockSummaryData_: {
            data: components["schemas"]["StockSummaryData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[SurgeData] */
        Envelope_SurgeData_: {
            data: components["schemas"]["SurgeData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[SurgeSearchData] */
        Envelope_SurgeSearchData_: {
            data: components["schemas"]["SurgeSearchData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** ErrorItem */
        ErrorItem: {
            /** At */
            at: string | null;
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Service Id */
            service_id: string;
            /** Summary */
            summary: string;
        };
        /** FreshnessItem */
        FreshnessItem: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "market";
            /** Latest At */
            latest_at: string | null;
            /** Latest Date */
            latest_date: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["StatusInfo"];
        };
        /** FreshnessSummary */
        FreshnessSummary: {
            /** Caveats */
            caveats: string[];
            /** Checked */
            checked: number;
            /** Late */
            late: string[];
            /** No Source */
            no_source: number;
            /** On Time */
            on_time: number;
        };
        /** GenerationInfo */
        GenerationInfo: {
            /** Age Seconds */
            age_seconds: number;
            /**
             * Built At
             * Format: date-time
             */
            built_at: string;
            /** Generation Id */
            generation_id: string;
            /** Previous Generation Id */
            previous_generation_id: string | null;
            /** Producer Commit */
            producer_commit: string;
            /** Published At */
            published_at: string | null;
            /** Schema Version */
            schema_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            counts: components["schemas"]["StateCounts"];
            /** Errors */
            errors: components["schemas"]["ErrorItem"][];
            /** Freshness */
            freshness: components["schemas"]["FreshnessItem"][];
            page_data: components["schemas"]["PageDataStatus"];
            /** Services */
            services: components["schemas"]["ServiceItem"][];
        };
        /** HoldingItem */
        HoldingItem: {
            /** Available Quantity */
            available_quantity: number;
            /** Average Cost */
            average_cost: number;
            /** Code */
            code: string;
            /** Market Price */
            market_price: number;
            /** Market Value */
            market_value: number;
            /** Name */
            name: string | null;
            /** Quantity */
            quantity: number;
            /** Unrealized Pct */
            unrealized_pct: number | null;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /** IntradayData */
        IntradayData: {
            /** Bars */
            bars: components["schemas"]["MinuteBar"][];
            /** Days */
            days: string[];
            /** Marks */
            marks: components["schemas"]["SurgeMark"][];
            /** Name */
            name: string | null;
            /** Ts Code */
            ts_code: string;
        };
        /** MarketInfo */
        MarketInfo: {
            /** Is Trading Day */
            is_trading_day: boolean | null;
            /** Next Trading Day */
            next_trading_day: string | null;
            phase: components["schemas"]["MarketPhase"];
            /** Phase Label */
            phase_label: string;
            /** Previous Trading Day */
            previous_trading_day: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /**
         * MarketPhase
         * @enum {string}
         */
        MarketPhase: "pre_open" | "call_auction" | "continuous" | "noon_break" | "closing_auction" | "after_close" | "non_trading_day" | "unknown";
        /** MemberRow */
        MemberRow: {
            /** Amount */
            amount: number | null;
            /** Is Limit Up */
            is_limit_up: boolean;
            /** Name */
            name: string | null;
            /** Pct Chg */
            pct_chg: number | null;
            /** Pools */
            pools: string[];
            /** Price */
            price: number | null;
            /** Rel Volume 5D */
            rel_volume_5d: number | null;
            /** Strength */
            strength: number | null;
            /** Ts Code */
            ts_code: string;
            /** Turnover Pct */
            turnover_pct: number | null;
        };
        /** MembersData */
        MembersData: {
            /** Board Code */
            board_code: string;
            /** Board Name */
            board_name: string | null;
            /** Rows */
            rows: components["schemas"]["MemberRow"][];
        };
        /** MetaData */
        MetaData: {
            /** Datasets */
            datasets: components["schemas"]["DatasetWatermarkInfo"][];
            generation: components["schemas"]["GenerationInfo"] | null;
            market: components["schemas"]["MarketInfo"];
            /** Projections */
            projections: components["schemas"]["ProjectionInfo"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Viewer */
            viewer: string | null;
        };
        /** MinuteBar */
        MinuteBar: {
            /** Avg Price */
            avg_price: number | null;
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "flat";
            /** Price */
            price: number;
            /** Slot */
            slot: number;
            /** T */
            t: string;
            /** Volume */
            volume: number | null;
        };
        /** OverviewData */
        OverviewData: {
            /** Attention */
            attention: components["schemas"]["AttentionItem"][];
            candidates: components["schemas"]["CandidatesSummary"];
            deliveries: components["schemas"]["DeliveriesSummary"];
            freshness: components["schemas"]["FreshnessSummary"];
            paper: components["schemas"]["PaperSummary"] | null;
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStage"][];
            services: components["schemas"]["StateCounts"];
            session: components["schemas"]["SessionInfo"];
            signals: components["schemas"]["SignalsSummary"];
        };
        /**
         * PageDataStatus
         * @description The Serving generation, in the owner's words (页面数据).
         */
        PageDataStatus: {
            /** Age Seconds */
            age_seconds: number | null;
            /** Built At */
            built_at: string | null;
            /** Generation Id */
            generation_id: string | null;
            /** Published At */
            published_at: string | null;
            status: components["schemas"]["StatusInfo"];
            /** Tables Total */
            tables_total: number;
            /** Unpublished */
            unpublished: components["schemas"]["TableItem"][];
        };
        /** PaperSummary */
        PaperSummary: {
            /** Account Id */
            account_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Cash */
            cash: number;
            /** Holdings */
            holdings: components["schemas"]["HoldingItem"][];
            /** Nav */
            nav: number;
            /** Note */
            note: string | null;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /** PipelineStage */
        PipelineStage: {
            /** Hint */
            hint: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * State
             * @enum {string}
             */
            state: "done" | "running" | "waiting" | "paused" | "late";
            /** State Label */
            state_label: string;
            /** Value */
            value: string | null;
            /** Window */
            window: string;
        };
        /** ProjectionInfo */
        ProjectionInfo: {
            /** Available */
            available: boolean;
            /** Available At */
            available_at: string | null;
            /** Owner Dataset Id */
            owner_dataset_id: string | null;
            /** Reason */
            reason: string | null;
            /** Table Name */
            table_name: string;
        };
        /** PulseAlert */
        PulseAlert: {
            /** Kind */
            kind: string;
            /** Kind Label */
            kind_label: string;
            /** Message */
            message: string;
            /** T */
            t: string;
        };
        /** PulseCounts */
        PulseCounts: {
            /** Broken */
            broken: number;
            /** Down */
            down: number;
            /** Flat */
            flat: number;
            /** Limit Down */
            limit_down: number;
            /** Limit Up */
            limit_up: number;
            /** Total */
            total: number;
            /** Up */
            up: number;
            /** Up Ratio Pct */
            up_ratio_pct: number | null;
        };
        /** PulseData */
        PulseData: {
            /** Age Seconds */
            age_seconds: number | null;
            /** Alerts */
            alerts: components["schemas"]["PulseAlert"][];
            /** As Of */
            as_of: string | null;
            counts: components["schemas"]["PulseCounts"] | null;
            freshness: components["schemas"]["StatusInfo"];
            /** History */
            history: components["schemas"]["PulsePoint"][];
            recent_alert: components["schemas"]["PulseAlert"] | null;
            /** Source */
            source: ("snapshot" | "history") | null;
            /** Trade Date */
            trade_date: string | null;
        };
        /** PulsePoint */
        PulsePoint: {
            /** Broken */
            broken: number | null;
            /** Limit Down */
            limit_down: number | null;
            /** Limit Up */
            limit_up: number | null;
            /** T */
            t: string;
            /** Up Ratio Pct */
            up_ratio_pct: number | null;
        };
        /** ScreenBlock */
        ScreenBlock: {
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Hint */
            hint: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Parameters */
            parameters: components["schemas"]["ScreenParameter"][];
        };
        /** ScreenCatalogData */
        ScreenCatalogData: {
            /** Available */
            available: boolean;
            /** Blocks */
            blocks: components["schemas"]["ScreenBlock"][];
            /** Dates */
            dates: string[];
        };
        /** ScreenCondition */
        ScreenCondition: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /** Key */
            key: string;
        };
        /** ScreenOption */
        ScreenOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** ScreenParameter */
        ScreenParameter: {
            /** Hint */
            hint?: string | null;
            /** Initial */
            initial: string | number | string[] | null;
            /**
             * Input
             * @enum {string}
             */
            input: "number" | "integer" | "choice" | "multi_choice" | "field" | "operand";
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Options */
            options?: components["schemas"]["ScreenOption"][];
            /** Required */
            required: boolean;
            /**
             * Scale
             * @default 1
             */
            scale: number;
        };
        /** ScreenRow */
        ScreenRow: {
            /** Close */
            close: number | null;
            /** Name */
            name: string | null;
            /** Pct Chg */
            pct_chg: number | null;
            /** Ts Code */
            ts_code: string;
        };
        /** ScreenRunData */
        ScreenRunData: {
            /** Base Count */
            base_count: number | null;
            /** Next Cursor */
            next_cursor: string | null;
            /** Rows */
            rows: components["schemas"]["ScreenRow"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "unavailable" | "no_date";
            /** Steps */
            steps: components["schemas"]["ScreenStep"][];
            /** Total */
            total: number | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** ScreenRunRequest */
        ScreenRunRequest: {
            /** Conditions */
            conditions: components["schemas"]["ScreenCondition"][];
            /** Cursor */
            cursor?: string | null;
            /**
             * Page Size
             * @default 20
             */
            page_size: number;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** ScreenStep */
        ScreenStep: {
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /** ServiceItem */
        ServiceItem: {
            /** Backlog Count */
            backlog_count: number;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Input Sequence */
            input_sequence: number;
            /** Last Error */
            last_error: string | null;
            /** Name */
            name: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Output Sequence */
            output_sequence: number;
            /** Plane */
            plane: string;
            /** Plane Label */
            plane_label: string;
            /** Raw Status */
            raw_status: string;
            /** Service Id */
            service_id: string;
            /** Stale */
            stale: boolean;
            status: components["schemas"]["StatusInfo"];
        };
        /** ServingMeta */
        ServingMeta: {
            /** Age Seconds */
            age_seconds: number | null;
            /** Built At */
            built_at: string | null;
            /** Detail */
            detail: string;
            /** Generation Id */
            generation_id: string | null;
            /** Message */
            message: string | null;
            state: components["schemas"]["ServingState"];
        };
        /**
         * ServingState
         * @enum {string}
         */
        ServingState: "ready" | "stale" | "degraded" | "unavailable";
        /**
         * SessionInfo
         * @description Which trading day the numbers are for.
         */
        SessionInfo: {
            /** Is Today */
            is_today: boolean;
            /** Next Trading Day */
            next_trading_day: string | null;
            phase: components["schemas"]["MarketPhase"];
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Trade Date */
            trade_date: string | null;
        };
        /** SignalItem */
        SignalItem: {
            /** Action */
            action: string;
            /** Action Label */
            action_label: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Code */
            code: string;
            /**
             * Delivery
             * @enum {string}
             */
            delivery: "delivered" | "recorded" | "unconfirmed" | "sending" | "failed" | "expired" | "none";
            /** Delivery Label */
            delivery_label: string;
            /** Name */
            name: string | null;
            /** Reasons */
            reasons: string[];
            /** Sequence */
            sequence: number;
            /** Signal Id */
            signal_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
        };
        /** SignalsSummary */
        SignalsSummary: {
            /** By Action */
            by_action: components["schemas"]["ActionCount"][];
            /** Items */
            items: components["schemas"]["SignalItem"][];
            /** Total */
            total: number;
        };
        /** StateCounts */
        StateCounts: {
            /** Crit */
            crit: number;
            /** Idle */
            idle: number;
            /** Ok */
            ok: number;
            /** Total */
            total: number;
            /** Waiting */
            waiting: number;
            /** Warn */
            warn: number;
        };
        /**
         * StatusInfo
         * @description One user-level status: state (colour + icon), a short word, a one-line reason.
         */
        StatusInfo: {
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            state: components["schemas"]["UserState"];
        };
        /** StockSearchData */
        StockSearchData: {
            /** Available */
            available: boolean;
            /** Query */
            query: string;
            /** Rows */
            rows: components["schemas"]["StockSearchRow"][];
            /** Truncated */
            truncated: boolean;
        };
        /** StockSearchRow */
        StockSearchRow: {
            /** Name */
            name: string;
            /** Ts Code */
            ts_code: string;
        };
        /** StockSummaryData */
        StockSummaryData: {
            /** As Of */
            as_of: string | null;
            /** Name */
            name: string | null;
            /** Pools */
            pools: string[];
            /** Price */
            price: number | null;
            /** Ts Code */
            ts_code: string;
        };
        /** SurgeConfig */
        SurgeConfig: {
            /** Boards */
            boards: string[];
            /** K Cum */
            k_cum: number;
            /** Ratio Cap */
            ratio_cap: number;
            /** Summary */
            summary: string;
        };
        /** SurgeData */
        SurgeData: {
            config: components["schemas"]["SurgeConfig"] | null;
            /** Dates */
            dates: string[];
            /** Rows */
            rows: components["schemas"]["SurgeRow"][];
            /** Trade Date */
            trade_date: string | null;
        };
        /** SurgeMark */
        SurgeMark: {
            /** Count */
            count: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Label */
            label: string;
            /** Price */
            price: number | null;
            /** Slot */
            slot: number;
            /** T */
            t: string;
        };
        /** SurgeRow */
        SurgeRow: {
            /** Confirmed At */
            confirmed_at: string;
            /** Cum Amount */
            cum_amount: number | null;
            /** Name */
            name: string | null;
            /** Pct Chg */
            pct_chg: number | null;
            /** Price */
            price: number | null;
            /** Rel Cum */
            rel_cum: number | null;
            /** Room To Limit Pct */
            room_to_limit_pct: number | null;
            /** Status */
            status: string;
            /** Status Label */
            status_label: string;
            /** Theme */
            theme: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Ts Code */
            ts_code: string;
        };
        /** SurgeSearchData */
        SurgeSearchData: {
            /** Query */
            query: string;
            /** Rows */
            rows: components["schemas"]["SurgeRow"][];
            /** Truncated */
            truncated: boolean;
        };
        /** TableItem */
        TableItem: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /**
         * UserState
         * @enum {string}
         */
        UserState: "ok" | "warn" | "crit" | "idle" | "waiting";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthData_"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MetaData_"];
                };
            };
        };
    };
    get_overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OverviewData_"];
                };
            };
        };
    };
    get_boards_api_v1_panorama_boards_get: {
        parameters: {
            query?: {
                system?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BoardsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_members_api_v1_panorama_boards__board_code__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MembersData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pulse_api_v1_panorama_pulse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PulseData_"];
                };
            };
        };
    };
    get_daily_api_v1_panorama_stocks__ts_code__daily_get: {
        parameters: {
            query?: {
                count?: number;
            };
            header?: never;
            path: {
                ts_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DailyData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intraday_api_v1_panorama_stocks__ts_code__intraday_get: {
        parameters: {
            query?: {
                days?: number;
                date?: string | null;
            };
            header?: never;
            path: {
                ts_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IntradayData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surge_api_v1_panorama_surge_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SurgeData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_surge_api_v1_panorama_surge_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SurgeSearchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blocks_api_v1_screen_blocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScreenCatalogData_"];
                };
            };
        };
    };
    run_screen_api_v1_screen_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScreenRunData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stocks_api_v1_stocks_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StockSearchData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_summary_api_v1_stocks__ts_code__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ts_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StockSummaryData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
