/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 告警规则 */
        get: operations["alert_rules_api_v1_alert_rules_get"];
        put?: never;
        /** 保存告警规则 */
        post: operations["save_alert_rule_api_v1_alert_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 告警时间线 */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认告警 */
        post: operations["ack_alert_api_v1_alerts_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 回测结果 */
        get: operations["backtests_api_v1_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 回测详情 */
        get: operations["backtest_detail_api_v1_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据中心 */
        get: operations["data_center_api_v1_data_center_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 因子检验列表 */
        get: operations["factors_api_v1_factors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factors/{factor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 因子检验详情 */
        get: operations["factor_detail_api_v1_factors__factor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 系统健康 */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 总览 */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panorama": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 市场全景 */
        get: operations["panorama_api_v1_panorama_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模拟盘 */
        get: operations["paper_api_v1_paper_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 池子 */
        get: operations["pools_api_v1_pools_get"];
        put?: never;
        /** 保存池子 */
        post: operations["save_pool_api_v1_pools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio-backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合回测列表 */
        get: operations["portfolio_backtests_api_v1_portfolio_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio-backtests/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合回测对比 */
        get: operations["portfolio_compare_api_v1_portfolio_backtests_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio-backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组合回测详情 */
        get: operations["portfolio_backtest_api_v1_portfolio_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 选股结果与排序 */
        get: operations["screen_api_v1_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 策略与版本 */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 加入自选 */
        post: operations["add_watch_api_v1_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckAlertRequest */
        AckAlertRequest: {
            /** Alert Id */
            alert_id: string;
        };
        /** AddWatchRequest */
        AddWatchRequest: {
            /** Code */
            code: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** AlertItem */
        AlertItem: {
            /** Acked At */
            acked_at?: string | null;
            /** Acked By */
            acked_by?: string | null;
            /** Alert Id */
            alert_id: string;
            /** At */
            at: string | null;
            /** Code */
            code: string;
            /** Level */
            level: string;
            /** Level Price */
            level_price: number | null;
            /** Name */
            name: string | null;
            /** Pool */
            pool: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Trigger Price */
            trigger_price: number | null;
            /** Trigger Type */
            trigger_type: string | null;
        };
        /** AlertRuleBody */
        AlertRuleBody: {
            /**
             * Cooldown Minutes
             * @default 0
             */
            cooldown_minutes: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Levels
             * @default []
             */
            levels: string[];
            /**
             * Pools
             * @default []
             */
            pools: ("pool1" | "pool2" | "manual")[];
            /** Rule Id */
            rule_id: string;
            /** Title */
            title: string;
        };
        /** AlertRuleRow */
        AlertRuleRow: {
            /**
             * Cooldown Minutes
             * @default 0
             */
            cooldown_minutes: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Levels
             * @default []
             */
            levels: string[];
            /**
             * Pools
             * @default []
             */
            pools: ("pool1" | "pool2" | "manual")[];
            /** Rule Id */
            rule_id: string;
            /** Saved At */
            saved_at?: string | null;
            /** Title */
            title: string;
        };
        /** AlertRulesData */
        AlertRulesData: {
            /** Rules */
            rules: components["schemas"]["AlertRuleRow"][];
        };
        /** AlertsData */
        AlertsData: {
            /** Items */
            items: components["schemas"]["AlertItem"][];
        };
        /** AuditReport */
        AuditReport: {
            /** Datasets */
            datasets: components["schemas"]["DatasetCoverage"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Open Days */
            open_days: number;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** BacktestDetailData */
        BacktestDetailData: {
            perf?: components["schemas"]["BacktestPerf"] | null;
            run: components["schemas"]["BacktestRun"];
            /** Trades */
            trades: components["schemas"]["BacktestTrade"][];
        };
        /** BacktestListData */
        BacktestListData: {
            /** Runs */
            runs: components["schemas"]["BacktestRun"][];
        };
        /**
         * BacktestPerf
         * @description Ratios are fractions (0.12 = 12%); ``method`` says how NAV was derived.
         */
        BacktestPerf: {
            /** Annualized Return */
            annualized_return: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
            benchmark?: components["schemas"]["BenchmarkStats"] | null;
            /** Calmar */
            calmar: number | null;
            /** Days */
            days: number;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Max Drawdown Days */
            max_drawdown_days: number | null;
            /** Method */
            method: string;
            /** Monthly */
            monthly: components["schemas"]["MonthlyReturn"][];
            /** Nav */
            nav: components["schemas"]["NavPoint"][];
            /** Payoff Ratio */
            payoff_ratio: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Total Return */
            total_return: number | null;
            /** Win Rate */
            win_rate: number | null;
        };
        /** BacktestRun */
        BacktestRun: {
            /** Best Ret Pct */
            best_ret_pct: number | null;
            /** Computed At */
            computed_at: string | null;
            /** End Date */
            end_date: string | null;
            /** Entry Mode */
            entry_mode: string;
            /** Mean Ret Pct */
            mean_ret_pct: number | null;
            /** Median Ret Pct */
            median_ret_pct: number | null;
            /** Profile Variant */
            profile_variant: string;
            /** Run Id */
            run_id: string;
            /** Start Date */
            start_date: string | null;
            /** Trades */
            trades: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
            /** Worst Ret Pct */
            worst_ret_pct: number | null;
        };
        /** BacktestTrade */
        BacktestTrade: {
            /** Code */
            code: string;
            /** Entry Price */
            entry_price: number | null;
            /** Entry Time */
            entry_time: string | null;
            /** Exit Price */
            exit_price: number | null;
            /** Exit Reason */
            exit_reason: string | null;
            /** Exit Time */
            exit_time: string | null;
            /** Name */
            name: string | null;
            /** Ret Pct */
            ret_pct: number | null;
            /** Signal Date */
            signal_date: string | null;
            /** Trade Id */
            trade_id: string;
        };
        /** BenchmarkStats */
        BenchmarkStats: {
            /** Alpha */
            alpha: number | null;
            /** Beta */
            beta: number | null;
            /** Code */
            code: string;
            /** Excess Return */
            excess_return: number | null;
            /** Information Ratio */
            information_ratio: number | null;
            /** Total Return */
            total_return: number;
        };
        /** BoardItem */
        BoardItem: {
            /** Amount */
            amount: number | null;
            /** Board Code */
            board_code: string;
            /** Board Name */
            board_name: string;
            /** Leading Stock */
            leading_stock: string | null;
            /** Limit Up Count */
            limit_up_count: number | null;
            /** Main Net Amount */
            main_net_amount: number | null;
            /** Pct Chg Median */
            pct_chg_median: number | null;
            /** Stock Count */
            stock_count: number | null;
            /** System */
            system: string;
        };
        /** CatalogDataset */
        CatalogDataset: {
            /** Category */
            category: string;
            /** Dataset Id */
            dataset_id: string;
            /** Fields */
            fields: components["schemas"]["CatalogField"][];
            /** Name */
            name: string;
            /** Primary Key */
            primary_key: string[];
            /** Purpose */
            purpose: string;
            /**
             * Sample Available
             * @default false
             */
            sample_available: boolean;
            /** Schema Available */
            schema_available: boolean;
            /** Sources */
            sources: string[];
            /** Table Name */
            table_name: string;
            /** Update Note */
            update_note: string;
            /** Visibility Note */
            visibility_note: string;
        };
        /** CatalogField */
        CatalogField: {
            /** Data Type */
            data_type: string;
            /** Description */
            description: string;
            /** Is Primary Key */
            is_primary_key: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string | null;
        };
        /** CommandReceipt */
        CommandReceipt: {
            /** Command Id */
            command_id?: string | null;
            /** Detail */
            detail?: string | null;
            /** Status */
            status: string;
        };
        /** DataCenterData */
        DataCenterData: {
            audit: components["schemas"]["AuditReport"] | null;
            /** Datasets */
            datasets: components["schemas"]["CatalogDataset"][];
        };
        /** DatasetCoverage */
        DatasetCoverage: {
            /** Dataset Id */
            dataset_id: string;
            /** Error */
            error?: string | null;
            /** Latest Date */
            latest_date: string | null;
            /** Missing Open Days */
            missing_open_days: string[];
            /** Required On Open Day */
            required_on_open_day: boolean;
            /** Rows In Window */
            rows_in_window: number;
            /** Table Name */
            table_name: string;
        };
        /** DecayPoint */
        DecayPoint: {
            /** Horizon */
            horizon: number;
            /** Mean Ic */
            mean_ic: number | null;
        };
        /** Envelope[AlertRulesData] */
        Envelope_AlertRulesData_: {
            data: components["schemas"]["AlertRulesData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[AlertsData] */
        Envelope_AlertsData_: {
            data: components["schemas"]["AlertsData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[BacktestDetailData] */
        Envelope_BacktestDetailData_: {
            data: components["schemas"]["BacktestDetailData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[BacktestListData] */
        Envelope_BacktestListData_: {
            data: components["schemas"]["BacktestListData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[DataCenterData] */
        Envelope_DataCenterData_: {
            data: components["schemas"]["DataCenterData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[FactorDetailData] */
        Envelope_FactorDetailData_: {
            data: components["schemas"]["FactorDetailData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[FactorListData] */
        Envelope_FactorListData_: {
            data: components["schemas"]["FactorListData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[HealthData] */
        Envelope_HealthData_: {
            data: components["schemas"]["HealthData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[MetaData] */
        Envelope_MetaData_: {
            data: components["schemas"]["MetaData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[OverviewData] */
        Envelope_OverviewData_: {
            data: components["schemas"]["OverviewData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PanoramaData] */
        Envelope_PanoramaData_: {
            data: components["schemas"]["PanoramaData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PaperData] */
        Envelope_PaperData_: {
            data: components["schemas"]["PaperData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PoolsData] */
        Envelope_PoolsData_: {
            data: components["schemas"]["PoolsData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PortfolioCompareData] */
        Envelope_PortfolioCompareData_: {
            data: components["schemas"]["PortfolioCompareData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PortfolioRunDetailData] */
        Envelope_PortfolioRunDetailData_: {
            data: components["schemas"]["PortfolioRunDetailData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[PortfolioRunListData] */
        Envelope_PortfolioRunListData_: {
            data: components["schemas"]["PortfolioRunListData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[ScreenData] */
        Envelope_ScreenData_: {
            data: components["schemas"]["ScreenData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** Envelope[StrategyListData] */
        Envelope_StrategyListData_: {
            data: components["schemas"]["StrategyListData"];
            serving: components["schemas"]["ServingMeta"];
        };
        /** FactorDetailData */
        FactorDetailData: {
            factor: components["schemas"]["FactorSummary"];
            result: components["schemas"]["FactorTestResult"];
            tracking?: components["schemas"]["FactorTracking"] | null;
        };
        /** FactorListData */
        FactorListData: {
            /** Factors */
            factors: components["schemas"]["FactorSummary"][];
        };
        /** FactorSummary */
        FactorSummary: {
            /** Days */
            days: number;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Expression */
            expression: string;
            /** Factor Id */
            factor_id: string;
            /** Horizon */
            horizon: number;
            /** Ic Ir */
            ic_ir: number | null;
            /** Long Short */
            long_short: number | null;
            /** Mean Ic */
            mean_ic: number | null;
            /** Name */
            name: string;
            /** Recent Ic */
            recent_ic?: number | null;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Tracked To */
            tracked_to?: string | null;
        };
        /** FactorTestResult */
        FactorTestResult: {
            /** Coverage */
            coverage: number;
            /** Days */
            days: number;
            /** Decay */
            decay: components["schemas"]["DecayPoint"][];
            /** Horizon */
            horizon: number;
            /** Ic Ir */
            ic_ir: number | null;
            /** Ic Series */
            ic_series: components["schemas"]["IcPoint"][];
            /** Long Short */
            long_short: number | null;
            /** Mean Ic */
            mean_ic: number | null;
            /** Positive Ratio */
            positive_ratio: number | null;
            /** Quantiles */
            quantiles: components["schemas"]["QuantileReturn"][];
            /** T Stat */
            t_stat: number | null;
        };
        /** FactorTracking */
        FactorTracking: {
            /** Factor Id */
            factor_id: string;
            /** Latest Date */
            latest_date: string | null;
            /** Points */
            points: components["schemas"]["TrackingPoint"][];
            /** Recent Ic */
            recent_ic: number | null;
            /** Research Ic */
            research_ic: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** FreshnessItem */
        FreshnessItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Freshness */
            freshness: components["schemas"]["FreshnessItem"][];
            /** Services */
            services: components["schemas"]["ServiceItem"][];
        };
        /** HoldingItem */
        HoldingItem: {
            /** Average Cost */
            average_cost: number;
            /** Code */
            code: string;
            /** Market Price */
            market_price: number;
            /** Market Value */
            market_value: number;
            /** Name */
            name: string | null;
            /** Quantity */
            quantity: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /** IcPoint */
        IcPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Ic */
            ic: number;
        };
        /** IndustryExposure */
        IndustryExposure: {
            /** Avg Weight */
            avg_weight: number;
            /** Deviation */
            deviation: number;
            /** Industry */
            industry: string;
            /** Pool Weight */
            pool_weight: number;
            /** Weight */
            weight: number;
        };
        /** Kpi */
        Kpi: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Tone */
            tone?: ("ok" | "warn" | "crit") | null;
            /** Value */
            value: string;
        };
        /** MarketPulse */
        MarketPulse: {
            /** Down */
            down: number;
            /** Flat */
            flat: number;
            /** Limit Down */
            limit_down: number;
            /** Limit Up */
            limit_up: number;
            /** Up */
            up: number;
        };
        /** MetaData */
        MetaData: {
            /**
             * App
             * @default rQuant
             */
            app: string;
            generation: components["schemas"]["ServingMeta"];
            /** Notice */
            notice?: string | null;
            /** Version */
            version: string;
        };
        /** MonthlyReturn */
        MonthlyReturn: {
            /** Month */
            month: number;
            /** Ret */
            ret: number;
            /** Year */
            year: number;
        };
        /** NavPoint */
        NavPoint: {
            /** Benchmark Nav */
            benchmark_nav?: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Drawdown */
            drawdown: number;
            /** Nav */
            nav: number;
        };
        /** OverfitStats */
        OverfitStats: {
            /** Dsr */
            dsr: number | null;
            /** Min Track Record Days */
            min_track_record_days: number | null;
            /** Observations */
            observations: number;
            /** Psr */
            psr: number | null;
            /** Sharpe Per Day */
            sharpe_per_day: number;
            /** Trials */
            trials: number;
        };
        /** OverviewData */
        OverviewData: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Signals */
            signals: components["schemas"]["SignalItem"][];
            /** Trade Date */
            trade_date: string | null;
        };
        /** PanoramaData */
        PanoramaData: {
            /** As Of */
            as_of: string | null;
            /** Boards */
            boards: components["schemas"]["BoardItem"][];
            pulse: components["schemas"]["MarketPulse"];
        };
        /** PaperAccount */
        PaperAccount: {
            /** Account Id */
            account_id: string;
            /** As Of */
            as_of: string | null;
            /** Cash */
            cash: number;
            /** Holdings */
            holdings: components["schemas"]["HoldingItem"][];
            /** Nav */
            nav: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /** PaperData */
        PaperData: {
            /** Accounts */
            accounts: components["schemas"]["PaperAccount"][];
        };
        /** PoolItem */
        PoolItem: {
            /** Description */
            description: string;
            /** Members */
            members: components["schemas"]["PoolMember"][];
            /** Name */
            name: string;
            /** Pool Refs */
            pool_refs: string[];
            /** Updated At */
            updated_at: string | null;
        };
        /** PoolMember */
        PoolMember: {
            /** Code */
            code: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string | null;
            /** Preset */
            preset: string;
        };
        /** PoolsData */
        PoolsData: {
            /** Pools */
            pools: components["schemas"]["PoolItem"][];
            /** Trade Date */
            trade_date: string | null;
        };
        /** PortfolioCompareData */
        PortfolioCompareData: {
            a: components["schemas"]["PortfolioCompareSide"];
            b: components["schemas"]["PortfolioCompareSide"];
        };
        /** PortfolioCompareSide */
        PortfolioCompareSide: {
            perf: components["schemas"]["BacktestPerf"] | null;
            run: components["schemas"]["PortfolioRunSummary"];
        };
        /** PortfolioOrder */
        PortfolioOrder: {
            /** Code */
            code: string;
            /** Fee */
            fee: number;
            /** Price */
            price: number | null;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string | null;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** PortfolioRunDetailData */
        PortfolioRunDetailData: {
            /**
             * Exposure
             * @default []
             */
            exposure: components["schemas"]["IndustryExposure"][];
            /** Holdings */
            holdings: {
                [key: string]: number;
            };
            /** Orders */
            orders: components["schemas"]["PortfolioOrder"][];
            overfit?: components["schemas"]["OverfitStats"] | null;
            perf: components["schemas"]["BacktestPerf"] | null;
            run: components["schemas"]["PortfolioRunSummary"];
        };
        /** PortfolioRunListData */
        PortfolioRunListData: {
            /** Runs */
            runs: components["schemas"]["PortfolioRunSummary"][];
        };
        /** PortfolioRunSummary */
        PortfolioRunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Filled */
            filled: number;
            /** Final Nav */
            final_nav: number | null;
            /** Max Positions */
            max_positions: number;
            /** Preset */
            preset: string;
            /** Rebalance Every */
            rebalance_every: number;
            /** Rejected */
            rejected: number;
            /** Run Id */
            run_id: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Strategy */
            strategy?: string | null;
            /** Title */
            title: string;
        };
        /** QuantileReturn */
        QuantileReturn: {
            /** Mean Return */
            mean_return: number;
            /** Quantile */
            quantile: number;
        };
        /** SavePoolRequest */
        SavePoolRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Pool Refs */
            pool_refs?: string[];
        };
        /** ScreenData */
        ScreenData: {
            /** Presets */
            presets: string[];
            /** Rows */
            rows: components["schemas"]["ScreenRow"][];
            /** Trade Date */
            trade_date: string | null;
        };
        /** ScreenRow */
        ScreenRow: {
            /** Close */
            close: number | null;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Pct Chg */
            pct_chg: number | null;
            /** Preset */
            preset: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** ServiceItem */
        ServiceItem: {
            /** Backlog Count */
            backlog_count: number;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Plane */
            plane: string;
            /** Service Id */
            service_id: string;
            /** Stale */
            stale: boolean;
            /** Status */
            status: string;
        };
        /** ServingMeta */
        ServingMeta: {
            /** Generated At */
            generated_at?: string | null;
            /** Generation Id */
            generation_id?: string | null;
            /** Message */
            message?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "stale" | "degraded" | "unavailable";
        };
        /** SignalItem */
        SignalItem: {
            /** Action */
            action: string;
            /** At */
            at: string | null;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Sequence */
            sequence: number;
            /** Strategy Id */
            strategy_id: string;
        };
        /** StrategyListData */
        StrategyListData: {
            /** Strategies */
            strategies: components["schemas"]["StrategyRow"][];
        };
        /** StrategyRow */
        StrategyRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Max Positions */
            max_positions: number;
            /** Method */
            method: string;
            /** Note */
            note: string;
            /** Preset */
            preset: string;
            /** Rebalance Every */
            rebalance_every: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
            /** Versions */
            versions: number;
        };
        /** TrackingPoint */
        TrackingPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Ic */
            ic: number;
            /** Rolling */
            rolling: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alert_rules_api_v1_alert_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AlertRulesData_"];
                };
            };
        };
    };
    save_alert_rule_api_v1_alert_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AlertsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alert_api_v1_alerts_ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtests_api_v1_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BacktestListData_"];
                };
            };
        };
    };
    backtest_detail_api_v1_backtests__run_id__get: {
        parameters: {
            query?: {
                entry_mode?: string | null;
                benchmark?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BacktestDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_center_api_v1_data_center_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DataCenterData_"];
                };
            };
        };
    };
    factors_api_v1_factors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FactorListData_"];
                };
            };
        };
    };
    factor_detail_api_v1_factors__factor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FactorDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthData_"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MetaData_"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OverviewData_"];
                };
            };
        };
    };
    panorama_api_v1_panorama_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PanoramaData_"];
                };
            };
        };
    };
    paper_api_v1_paper_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PaperData_"];
                };
            };
        };
    };
    pools_api_v1_pools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PoolsData_"];
                };
            };
        };
    };
    save_pool_api_v1_pools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePoolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_backtests_api_v1_portfolio_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PortfolioRunListData_"];
                };
            };
        };
    };
    portfolio_compare_api_v1_portfolio_backtests_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
                benchmark?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PortfolioCompareData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_backtest_api_v1_portfolio_backtests__run_id__get: {
        parameters: {
            query?: {
                benchmark?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PortfolioRunDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screen_get: {
        parameters: {
            query?: {
                trade_date?: string | null;
                preset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScreenData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StrategyListData_"];
                };
            };
        };
    };
    add_watch_api_v1_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
