"""Go-live criterion (3b): one signal travelling the whole live chain on an open day.

Every Route A e2e in this repository so far has been built out of a window where nothing
traded. `test_route_a_live_chain_idle_e2e.py` starts the six live-plane roles in the
runbook's order and closes with `#: and nothing on the chain produced a signal, which is
the premise`; `test_route_a_window7_gaps_e2e.py` moved the clock into a session but only
for the two source roles; `test_route_a_readside_replica_e2e.py` places a world on a
trading day but stops at the candidate universe. So the chain's second half --
`feature_live` writing a feature batch, a strategy emitting a signal, `signal_router`
routing it, `paper_broker` booking it, `notifier` turning it into a delivery, and
`serving_publisher` putting a same-day generation under `serving/generations/` -- has
never run in a test at all.

This file is that run, over the world the host actually has:

* **two real installed generations**, the second over the first, which is the install that
  prepares the schema rollout plans every kind-backed role opens on its way in (#227/#229),
  acknowledged the way the runbook acknowledges them;
* a **real staged and published authority chain**, the wrapper's own argv and child
  environment, and **each role inside its own unit's `ReadWritePaths`**, read verbatim out
  of `deploy/systemd/` by the package-L harness this file drives;
* **all four external inputs real**. Package J made three of them real in `cold_chain` --
  the frozen routing policy, a real Ed25519 Shadow completion key, and the paper broker's
  PIT trade calendar. The fourth, the historical minute parquet `feature_live` hashes at
  start-up, was a zero-row placeholder in every world in the repository, because
  `_production_bundle` overwrote whatever `_inputs` had written with an empty frame before
  taking the sha256 it records. It is now generated by the production generator itself,
  `scripts/export_intraday_snapshot.py`, out of a fixture DuckDB holding 1-minute
  `minute_bar` rows for three codes over two trading days;
* a **clock inside a trading session on a day the bundle's calendar opens**, using the
  `in_session` technique from the seventh window's file -- but applied, for the first time,
  to the roles of the signal chain rather than to the two sources in front of them.

What the harness supplies is what a producer would have put on disk: minute batches in
`live/market-minute` written through `MarketMinuteGateway`, the same writer
`market_minute_source` uses, and candidate snapshots written through
`StrategyCandidateSnapshotSpool.publish_strategy_records`, the same writer
`candidate_publisher` calls (the seam package N states and the seventh window's file
already uses). Everything downstream of those two writers is the real role, built by the
real builder, from the real manifest, inside the real sandbox.

The negative half carries the same weight as the positive one: a candidate document dated
anything but today is refused by the loader, a signal receipt with one byte changed is
refused by the router, and serving does not cut a second generation for content that has
not moved.
"""

from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import time
from contextlib import closing
from datetime import UTC, date, datetime, timedelta
from datetime import time as clock_time
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import pandas as pd
import pytest

import tests.integration.test_route_a_all_roles_sandbox_e2e as harness
from rquant.live_spool import LiveBatchSpool
from rquant.market_minute_gateway import MarketMinuteGateway, MarketMinuteGatewayConfig
from rquant.runtime_capabilities import RUNTIME_CAPABILITY_CREDENTIAL_NAME
from rquant.runtime_deployment_bundle import acknowledge_runtime_schema_rollout_preparation
from rquant.strategy_candidate_snapshot import (
    StrategyCandidatePriceBasis,
    StrategyCandidateRecord,
    StrategyCandidateSnapshotSpool,
)
from tests.integration.test_route_a_all_roles_sandbox_e2e import (
    CREDSTORE_ROLES,
    ROLE_UNITS,
    instance_of,
)
from tests.integration.test_route_a_legacy_binding_e2e import RouteAWorld, _production_bundle
from tests.integration.test_route_a_live_chain_idle_e2e import PREVIOUS_COMMIT, _instance_name
from tests.integration.test_route_a_strategy_chain_e2e import _routing_policy_payload
from tests.shadow_ed25519_support import create_shadow_ed25519_test_authority
from tests.support.systemd_credential_delivery import deliver
from tests.unit.test_runtime_authority_publish import World

pytestmark = pytest.mark.integration

_SHANGHAI = ZoneInfo("Asia/Shanghai")

#: The session this file trades, and the sessions in front of it. Fixed dates rather than
#: "tomorrow", because every comparison on this path is against an explicit instant and
#: the world has to be placed where the calendar the bundle installs actually opens.
OPEN_DATES = (
    date(2026, 8, 3),
    date(2026, 8, 4),
    date(2026, 8, 5),
    date(2026, 8, 6),
    date(2026, 8, 7),
    date(2026, 8, 10),
    date(2026, 8, 11),
)
TRADE_DATE = OPEN_DATES[-1]
#: the two sessions the historical minute parquet is exported from: both open, both before
#: the session that trades, so nothing in the sealed history is same-day evidence
HISTORY_DATES = (OPEN_DATES[-3], OPEN_DATES[-2])
#: The paper broker's PIT calendar has to run past the session, because settling a buy
#: needs the *next* open day: `runtime_paper_quote` refuses with "frozen calendar has no
#: next SSE open day after <date>" when the session it is trading is the calendar's last
#: entry. The market calendar the bundle installs stays at `OPEN_DATES`; only the PIT
#: document the broker hashes carries the two sessions after it.
PIT_DATES = (*OPEN_DATES, date(2026, 8, 12), date(2026, 8, 13))

#: Three codes, one per exchange prefix the cost engine's selectors cover, so the paper
#: broker's instrument context resolves and the minute history is not a single series.
CODES = ("000001.SZ", "600000.SH", "601398.SH")
#: the one `n_shape` trades in this file
SIGNAL_CODE = "600000.SH"


def _at(hour: int, minute: int, second: int = 0, *, day: date = TRADE_DATE) -> datetime:
    """A Shanghai wall-clock instant on `day`, as the aware UTC the roles are given."""

    return datetime.combine(
        day, clock_time(hour, minute, second), tzinfo=_SHANGHAI
    ).astimezone(UTC)


#: 09:47:37 Shanghai -- inside the continuous session, after the 09:31-09:45 auction
#: assembly window, and deliberately off-phase. Package Y's review found a defect that
#: every test had walked past because every instant in it sat exactly on a boundary, so
#: no instant in this file is a round minute of anything the code compares against.
SESSION_NOW = _at(9, 47, 37)
#: when the minute batch the feature role consumes was received: one minute back, so the
#: bar is complete and inside the paper broker's `quote_max_age_seconds` of 90
MINUTE_RECEIVED_AT = _at(9, 47, 11)
#: when the candidate snapshots were captured: before the open, as a publisher that ran in
#: its 08:45 window would have left them
CANDIDATES_CAPTURED_AT = _at(8, 47, 11)
#: The second install's schema rollout start. It used to have to be opened at the market
#: clock and early enough that the whole chain -- `HOP_CLOCKS`, 09:47:17 to 09:48:53 -- ran
#: inside the profile's 600-second stage timeout, because the install staged a plan for
#: every two-sided channel and every producer dual-wrote under it. Since #228 the install
#: stages none (the two generations differ only in their commit), so nothing here depends on
#: it any more; it is kept so the install and the acknowledgement run at the same instants.
SCHEMA_ROLLOUT_STARTED_AT = _at(9, 44, 11)
#: when the replica-sync timer last replaced the read-only replica the notifier reads
REPLICA_SYNCED_AT = _at(9, 22, 47)
#: The instants the later hops run at. The paper broker's `execution_lag_seconds` is 60,
#: so a signal routed at `SESSION_NOW` is not executable until a minute later.
ROUTER_NOW = _at(9, 48, 3)
BROKER_NOW = _at(9, 48, 19)
NOTIFIER_NOW = _at(9, 48, 37)
SERVING_NOW = _at(9, 48, 53)

FEATURE_ROLE = "feature_live"
STRATEGY_ROLE = "strategy_live"
ROUTER_ROLE = "signal_router"
BROKER_ROLE = "paper_broker"
CONSTRAINT_ROLE = "paper_constraint_publisher"
NOTIFIER_ROLE = "notifier"
SERVING_ROLE = "serving_publisher"
HEALTH_ROLE = "runtime_health_publisher"
LAB_JOBS_ROLE = "lab_jobs_publisher"
REFERENCE_SOURCE_ROLE = "reference_slow_source"
REFERENCE_PUBLISHER_ROLE = "reference_slow_publisher"

N_SHAPE_SERVICE_ID = "strategy.n_shape.v1"
N_SHAPE_CANDIDATE_SERVICE_ID = "candidate.n_shape.v1"
CONSTRAINT_SERVICE_ID = "paper-constraint.market.v1"


# ---------------------------------------------------------------------------------------
# The fourth real input: a historical minute parquet from the production generator
# ---------------------------------------------------------------------------------------


def _minute_history_frame() -> pd.DataFrame:
    """1-minute `minute_bar` rows for three codes over two open sessions.

    Shaped the way the production table is shaped -- `source`/`freq` columns, one row per
    `(ts_code, trade_time)` -- because `export_intraday_snapshot.read_snapshot_frame`
    queries it with the production query and the production primary key in mind.
    """

    rows: list[dict[str, Any]] = []
    for day in HISTORY_DATES:
        for index, code in enumerate(CODES):
            base = 10.0 + index
            for step in range(30):  # 09:31 .. 10:00, bar-end timestamps
                stamp = datetime.combine(day, clock_time(9, 31)) + timedelta(minutes=step)
                close = round(base + 0.01 * step, 4)
                volume = 1_000.0 + 10.0 * step
                rows.append(
                    {
                        "ts_code": code,
                        "trade_time": stamp,
                        "freq": "1min",
                        "open": round(close - 0.01, 4),
                        "high": round(close + 0.02, 4),
                        "low": round(close - 0.02, 4),
                        "close": close,
                        "vol": volume,
                        "amount": round(volume * close, 4),
                        "source": "tushare",
                    }
                )
    return pd.DataFrame(rows)


@pytest.fixture(scope="session")
def minute_history_parquet(tmp_path_factory: pytest.TempPathFactory) -> bytes:
    """The sealed history, generated by `scripts/export_intraday_snapshot.py` itself.

    Not a frame written by this file: the export is the production path, and running it
    here is what makes the bytes `feature_live` hashes the bytes an operator would have
    produced. It re-shapes the rows into `intraday_feature_engine.INPUT_COLUMNS`, derives
    `available_at` under bar-end semantics, and -- the guard that matters -- runs the
    consumer's own `_normalize_frame` over the result, so a history the feature role would
    refuse at start-up fails here instead.

    Session-scoped because it is a pure function of this module's constants and the export
    opens a DuckDB file; the bytes are handed to each world's `_inputs` unchanged.
    """

    import sys

    scripts = Path(__file__).resolve().parents[2] / "scripts"
    if str(scripts) not in sys.path:  # pragma: no cover - import bootstrap
        sys.path.insert(0, str(scripts))
    import duckdb
    from export_intraday_snapshot import read_snapshot_frame, write_snapshot

    root = tmp_path_factory.mktemp("minute-history")
    database = root / "rquant_ro.duckdb"
    frame = _minute_history_frame()
    connection = duckdb.connect(str(database))
    try:
        connection.execute(
            """
            CREATE TABLE minute_bar (
                ts_code VARCHAR NOT NULL,
                trade_time TIMESTAMP NOT NULL,
                freq VARCHAR NOT NULL,
                open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE,
                vol DOUBLE, amount DOUBLE,
                source VARCHAR DEFAULT 'tushare',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (ts_code, trade_time, freq, source)
            )
            """
        )
        connection.register("history", frame)
        connection.execute(
            "INSERT INTO minute_bar (ts_code, trade_time, freq, open, high, low, close, "
            "vol, amount, source) SELECT ts_code, trade_time, freq, open, high, low, "
            "close, vol, amount, source FROM history"
        )
    finally:
        connection.close()

    #: the generator refuses a database named `rquant.duckdb` outright (DuckDB's single
    #: write lock), which is why the fixture file carries the replica's name
    exported, trade_dates = read_snapshot_frame(
        database,
        sessions=len(HISTORY_DATES),
        source="tushare",
        freq="1min",
        availability_lag_seconds=0,
        allow_primary_database=False,
    )
    output = root / "minute-history.parquet"
    write_snapshot(exported, output)

    assert tuple(trade_dates) == HISTORY_DATES
    assert sorted(exported["ts_code"].unique()) == sorted(CODES)
    assert len(exported) == len(CODES) * len(HISTORY_DATES) * 30
    return output.read_bytes()


def test_the_sealed_history_is_a_real_export_of_three_codes_over_two_sessions(
    minute_history_parquet: bytes,
) -> None:
    """The premise of the world, asserted before the world is built on it.

    Every Route A world before this one installed a parquet with the nine columns and no
    rows, so `feature_live` could start and could never compute a feature that needed a
    prior session. A test that only checked "the role started" would pass on both.
    """

    import io

    frame = pd.read_parquet(io.BytesIO(minute_history_parquet))

    assert len(frame) == len(CODES) * len(HISTORY_DATES) * 30
    assert sorted(frame["ts_code"].unique()) == sorted(CODES)
    assert sorted({stamp.date() for stamp in frame["trade_time"]}) == sorted(HISTORY_DATES)
    #: one bar per code-minute, which is what the feature engine refuses to guess about
    assert not frame.duplicated(subset=["ts_code", "trade_time"]).any()
    #: bar-end semantics: the bar is available when it closes
    assert (frame["available_at"] == frame["trade_time"]).all()
    #: and every session is before the one that trades
    assert max(stamp.date() for stamp in frame["trade_time"]) < TRADE_DATE


# ---------------------------------------------------------------------------------------
# The world
# ---------------------------------------------------------------------------------------


#: when a host that ran the two pre-open reference roles would have published: before the
#: session, because `paper_constraint_publisher` refuses evidence from its own future
REFERENCE_PUBLISHED_AT = _at(9, 4, 13)


def publish_reference_generation(path: Path) -> None:
    """One published reference generation covering every code the minute batch carries.

    `paper_constraint_publisher` resolves four datasets per code and refuses a code it has
    no evidence for, so the generation has to span the whole batch rather than one symbol.
    Written through `ReferenceRegistry` itself, which is what `reference_slow_publisher`
    calls, so what lands is what that role would have left at 09:0x.
    """

    from rquant.reference_data_registry import (
        ReferenceDataset,
        ReferenceRecord,
        ReferenceRegistry,
    )

    registry = ReferenceRegistry(path)
    effective_from = _at(0, 0)
    for code in CODES:
        for dataset, payload in (
            (ReferenceDataset.ST_STATUS, {"is_st": False}),
            (ReferenceDataset.SUSPENSION_STATUS, {"is_suspended": False}),
            (
                ReferenceDataset.LISTING_STATUS,
                {
                    "status": "listed",
                    #: `_required_a_share_instrument_context` builds the broker's
                    #: instrument context out of these four and refuses anything that is
                    #: not a CN A-share equity, which is also what the cost engine's
                    #: selectors key on
                    "market": "CN",
                    "exchange": "SSE" if code.endswith(".SH") else "SZSE",
                    "instrument_class": "EQUITY",
                    "security_class": "A_SHARE",
                },
            ),
            (
                ReferenceDataset.PRICE_LIMIT_REGIME,
                {
                    "limit_eligible": True,
                    "limit_percent": 0.1,
                    #: the same limit the `n_shape` candidate document states, so the
                    #: evaluator's `below_limit` and the broker's own limit agree
                    "limit_up_price": 12.1,
                    "limit_down_price": 9.9,
                },
            ),
        ):
            registry.append(
                ReferenceRecord(
                    dataset_id=dataset,
                    key=code,
                    effective_from=effective_from,
                    revision=1,
                    source="test.reference",
                    first_available_at=REFERENCE_PUBLISHED_AT,
                    payload=payload,
                )
            )
    registry.publish(published_at=REFERENCE_PUBLISHED_AT)


#: The serving publisher reads six source authorities and fails closed if any one of them
#: is unreadable. Two are hops of this chain and are produced by the real roles here --
#: `signals` by the notifier, `paper_accounts` by the paper broker -- and `runtime_health`
#: is published by `runtime_health_publisher`, which is in the chain for that reason. The
#: remaining three belong to the research and reference planes: their owners are pre-open
#: or research-plane roles that are not on the signal path at all, so their artifact is
#: written by the same publisher those roles use and the session starts with it in place.
OFF_CHAIN_SERVING_AUTHORITIES: tuple[tuple[str, str], ...] = (
    ("lab_jobs", "lab_jobs"),
    ("promotions", "promotions"),
    ("reference_slow_authority", "reference_slow"),
)


def publish_off_chain_serving_authorities(
    route: RouteAWorld,
    *,
    unpublished: frozenset[str] = frozenset(),
) -> None:
    """One published generation per off-chain serving source, through its own publisher.

    `unpublished` leaves an authority root untouched, which is what the host actually
    shows for the two research datasets: `research/serving-authorities/lab-jobs` and
    `.../promotions` have never held a generation, because neither research role has run
    (#283).
    """

    from rquant.runtime_contracts import canonical_sha256
    from rquant.runtime_serving_authority import ServingSourceAuthorityPublisher
    from rquant.runtime_serving_snapshot import (
        LabJobsPayload,
        PromotionsPayload,
        ReferenceSlowPayload,
        SourceReadResult,
    )
    from rquant.serving_contracts import FreshnessStatus

    payloads: dict[str, Any] = {
        "lab_jobs": LabJobsPayload(),
        "promotions": PromotionsPayload(),
        #: the reference plane's own evidence: which published generation the serving
        #: row was built from, and on what price and adjustment basis
        "reference_slow": ReferenceSlowPayload(
            reference_generation_id="b" * 64,
            revision=1,
            price_basis="raw_session",
            adjustment_basis="tushare_adj_factor",
            available_at=REFERENCE_PUBLISHED_AT,
        ),
    }
    manifest = manifest_of(route, "serving.publisher.v1")
    roots = {
        str(dict(entry)["dataset_id"]): Path(str(dict(entry)["root"]))
        for entry in manifest.settings["source_authorities"]
    }
    for dataset_id, payload_kind in OFF_CHAIN_SERVING_AUTHORITIES:
        if dataset_id in unpublished:
            continue
        values: dict[str, Any] = {
            "dataset_id": dataset_id,
            "sequence": 1,
            "event_time": REFERENCE_PUBLISHED_AT,
            "published_at": REFERENCE_PUBLISHED_AT,
            "status": FreshnessStatus.FRESH,
            "reason": None,
            "payload": payloads[payload_kind],
        }
        values["generation_id"] = canonical_sha256(values)
        ServingSourceAuthorityPublisher(
            root=roots[dataset_id],
            producer_commit=route.world.commit,
            dataset_id=dataset_id,
            payload_kind=payload_kind,
            clock=lambda: REFERENCE_PUBLISHED_AT,
        ).publish(SourceReadResult.model_validate(values))


def write_projection_replica(path: Path) -> None:
    """The read-only replica the notifier's page projection opens, with the tables it needs.

    `scripts/sync-readonly-replica.sh` leaves a WAL-free 0644 copy of the main database,
    which is why the readers' mode rule allows 0644 (#249). `DuckDBSignalPageProjectionSource`
    refuses a projection database without both `screen_result` and `minute_bar`, so a
    replica carrying only `daily_bar` -- which is all the read-side file's world needs --
    takes this role DEGRADED on every iteration. The mtime is the instant the timer last
    replaced it, before anything in this file reads it, because every reader on this path
    refuses evidence from its own future.
    """

    import duckdb

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.unlink()
    connection = duckdb.connect(str(path))
    try:
        connection.execute(
            """
            CREATE TABLE daily_bar(ts_code VARCHAR, trade_date DATE, vol DOUBLE);
            CREATE TABLE screen_result (
                trade_date DATE, preset_name VARCHAR, ts_code VARCHAR, name VARCHAR,
                close DOUBLE, pct_chg DOUBLE, extra JSON, created_at TIMESTAMP
            );
            CREATE TABLE minute_bar (
                ts_code VARCHAR, trade_time TIMESTAMP, freq VARCHAR, open DOUBLE,
                high DOUBLE, low DOUBLE, close DOUBLE, vol DOUBLE, amount DOUBLE,
                source VARCHAR, created_at TIMESTAMP
            );
            """
        )
        connection.executemany(
            "INSERT INTO daily_bar VALUES (?, ?, ?)",
            [(SIGNAL_CODE, day, 1_000.0) for day in OPEN_DATES[:-1]],
        )
        connection.execute(
            "INSERT INTO screen_result VALUES (?, 'n-shape-pool1', ?, '浦发银行', 10.6, 6, "
            "'{}', ?)",
            [
                OPEN_DATES[-2],
                SIGNAL_CODE,
                datetime.combine(OPEN_DATES[-2], clock_time(15, 5)),
            ],
        )
        connection.execute(
            "INSERT INTO minute_bar SELECT ?, TIMESTAMP '"
            + f"{OPEN_DATES[-2].isoformat()} 09:30:00"
            + "' + range * INTERVAL 1 MINUTE, '1min', 10, 10.6, 10, 10.6, 100, 1000, "
            "'tushare', ? FROM range(240)",
            [SIGNAL_CODE, datetime.combine(OPEN_DATES[-2], clock_time(15, 5))],
        )
        connection.execute("CHECKPOINT")
    finally:
        connection.close()
    assert not Path(f"{path}.wal").exists()
    path.chmod(0o644)
    stamp = REPLICA_SYNCED_AT.timestamp()
    os.utime(path, (stamp, stamp))


def _pit_trade_calendar_payload() -> bytes:
    from build_runtime_production_inputs import build_pit_trade_calendar_payload

    generated_at = datetime.combine(OPEN_DATES[0], clock_time(0, 0), tzinfo=UTC)
    return build_pit_trade_calendar_payload(
        tuple((day, True, generated_at) for day in PIT_DATES)
    )


def _freeze_before_the_session(path: Path) -> None:
    """Backdate a frozen input's mtime to before the session clock.

    `runtime_routing_policy._read_frozen_policy` refuses a policy file whose mtime is in
    the future of the observing clock. Every fixture file is written while the suite runs,
    which is after the session this world is placed in, so on the host's own timeline the
    policy would be from the future. Backdating is what makes the fixture's timeline the
    host's: a frozen document is frozen before the session that reads it.
    """

    stamp = (SESSION_NOW - timedelta(days=1)).timestamp()
    os.utime(path, (stamp, stamp))


class _RecordingProvider:
    """A notification provider that confirms delivery instead of reaching the network.

    The notifier's default provider loader builds a real PushDeer/PushPlus client out of
    the capability credential the bundle sealed, and a real client posts to
    `api2.pushdeer.com`. Left alone it does exactly that: the first run of this file took
    the notifier hop from 0.87s to 2.58s and recorded `notifier:unknown_outcomes:2`,
    because nothing answered -- which is the notifier behaving correctly and the test
    behaving badly. No case in this repository is allowed to touch the network outside
    `-m network`, and an outcome that depends on an endpoint answering is not evidence.

    Only the transport is replaced. The claim, the lease, the attempt row and the receipt
    are all the real `run_notification_batch`.
    """

    def __init__(self) -> None:
        self.deliveries: list[Any] = []

    def deliver(self, delivery: Any) -> str:
        self.deliveries.append(delivery)
        return f"test:{len(self.deliveries)}"


def confirm_deliveries_without_the_network(monkeypatch: pytest.MonkeyPatch) -> _RecordingProvider:
    """Swap every channel's provider for a recording one, keeping the registry real."""

    import rquant.runtime_notification_providers as providers_module

    recorder = _RecordingProvider()
    real_loader = providers_module.build_environment_notification_provider_loader

    def loader_with_a_recording_transport(**kwargs: Any) -> Any:
        real = real_loader(**kwargs)

        def load() -> Any:
            registry = real()
            return providers_module.RecipientScopedProviderRegistry(
                providers={channel: recorder for channel in registry},
                recipient_ids={
                    channel: registry.recipient_ids.get(channel, ()) for channel in registry
                },
                inferred_channels=registry.recipient_preflight.inferred_channels,
            )

        return load

    monkeypatch.setattr(
        providers_module,
        "build_environment_notification_provider_loader",
        loader_with_a_recording_transport,
    )
    return recorder


def build_trading_day_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
    *,
    notifier_delivery_mode: str = "shadow",
    unpublished_authorities: frozenset[str] = frozenset(),
    bundle_out: dict[str, Any] | None = None,
    capability_overrides: dict[str, str] | None = None,
) -> RouteAWorld:
    """Two acknowledged generations on an open day, with all four inputs real.

    `notifier_delivery_mode` is the #281 profile input, and it is set here rather than by
    editing the built manifest: the three worlds below differ by one value in the inputs
    document, and everything between that value and the notifier's behaviour -- the
    generator, `build_production_runtime_profile`, the manifest, `NotifierSettings` -- is
    the production path. The default is the profile's own default, `shadow`.

    Package J's `cold_chain` with three changes, each one forced by the premise:

    * the market calendar opens the session that trades and the six before it, rather than
      the single date a world that never trades needs;
    * the schema rollout window is stamped at the market clock, because a producer records
      its dual-write with the service's clock and the store refuses a record outside the
      window;
    * the historical minute parquet is the real export, installed through `_inputs` and
      kept -- which it could not be until `_production_bundle` stopped overwriting it.

    `bundle_out`, when given, receives what installing the next generation over this world
    needs and the world does not otherwise keep: the target bundle's `inputs` and the
    capability environment it was installed with (the notifier cutover rehearsal), and
    `capability_overrides` is handed to both installs unchanged.
    """

    import tests.unit.test_runtime_production_profile as profile_fixtures

    authority = create_shadow_ed25519_test_authority(tmp_path / "shadow-completion-keys")
    public_key_pem = authority.keyring._keys[authority.keyring.active_key_id].decode("utf-8")
    policy_payload = _routing_policy_payload()  # this puts `scripts` on `sys.path`
    trade_calendar_payload = _pit_trade_calendar_payload()
    real_inputs = profile_fixtures._inputs

    def real_external_inputs(path: Path) -> Any:
        inputs = real_inputs(path)
        for target, payload, mode in (
            (Path(inputs.routing_policy_path), policy_payload, 0o444),
            (Path(inputs.trade_calendar_path), trade_calendar_payload, 0o600),
            (Path(inputs.historical_minutes_snapshot_path), minute_history_parquet, 0o600),
        ):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
            target.chmod(mode)
        return inputs.model_copy(
            update={
                "notifier_delivery_mode": notifier_delivery_mode,
                "shadow_completion_active_key_id": authority.keyring.active_key_id,
                "shadow_completion_active_public_key_pem": public_key_pem,
                "routing_policy_fingerprint": hashlib.sha256(policy_payload).hexdigest(),
                "trade_calendar_sha256": hashlib.sha256(trade_calendar_payload).hexdigest(),
                "historical_minutes_snapshot_id": hashlib.sha256(
                    minute_history_parquet
                ).hexdigest(),
            }
        )

    monkeypatch.setattr(profile_fixtures, "_inputs", real_external_inputs)

    world = World(tmp_path / "root", monkeypatch).build()
    runtime_root = tmp_path / "host" / "data" / "runtime"
    capabilities: dict[str, str] = {}
    _production_bundle(
        tmp_path / "previous",
        monkeypatch,
        producer_commit=PREVIOUS_COMMIT,
        runtime_root=runtime_root,
        schema_bootstrap_reason="criterion (3b) acceptance bootstrap",
        market_calendar_open_dates=OPEN_DATES,
        capability_overrides=capability_overrides,
    )
    inputs, profile, receipt, sealed = _production_bundle(
        tmp_path / "target",
        monkeypatch,
        producer_commit=world.commit,
        runtime_root=runtime_root,
        #: only the first install into an empty root may carry a bootstrap reason, and the
        #: second install without one is what used to prepare the rollout plans
        schema_bootstrap_reason=None,
        #: one registry root cannot hold two commits' definitions (#225)
        definition_registry_root=runtime_root.parent / f"definitions-{world.commit[:7]}",
        market_calendar_open_dates=OPEN_DATES,
        schema_rollout_started_at=SCHEMA_ROLLOUT_STARTED_AT,
        capabilities_out=capabilities,
        capability_overrides=capability_overrides,
    )
    if bundle_out is not None:
        bundle_out["inputs"] = inputs
        bundle_out["capabilities"] = capabilities
    assert receipt.previous_generation_hash is not None
    #: no channel's shape moved, so no plan (#228) and no producer bound to a dual-write
    #: window it would have to carry through the session (#304)
    assert receipt.schema_rollout_plan_ids == ()

    #: `_production_bundle` relocates every external input under `<runtime root>/../external`
    #: and the roles read the relocated paths, so the documents the profile carries only a
    #: hash of are written there too -- the same bytes, so the hashes still hold.
    for target, payload, mode in (
        (Path(inputs.routing_policy_path), policy_payload, 0o444),
        (Path(inputs.trade_calendar_path), trade_calendar_payload, 0o600),
        (Path(inputs.historical_minutes_snapshot_path), minute_history_parquet, 0o600),
    ):
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)
        target.chmod(mode)
        _freeze_before_the_session(target)

    route = RouteAWorld(world, inputs.runtime_root)
    route.profile = profile
    route.receipt = receipt
    route.sealed_credentials = sealed
    route.stage_and_publish()
    #: `rquant runtime-schema-rollout acknowledge`, the runbook step between B-7 and C-3,
    #: inside the window the install just opened
    acknowledge_runtime_schema_rollout_preparation(
        route.runtime_root, now=SCHEMA_ROLLOUT_STARTED_AT + timedelta(seconds=37)
    )
    #: the read-only replica the notifier's page projection opens (#250/#268), and the
    #: reference generation `paper_constraint_publisher` resolves every quote against
    write_projection_replica(Path(inputs.readonly_replica_database_path))
    publish_reference_generation(
        setting_of(route, CONSTRAINT_SERVICE_ID, "reference_registry_path")
    )
    publish_off_chain_serving_authorities(route, unpublished=unpublished_authorities)
    return route


@pytest.fixture
def trading_day_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
) -> RouteAWorld:
    """The world with the notifier on its emergency stop, `notifier_delivery_mode=paused`.

    This was the shipped profile until #281 made the mode an input; it is now the mode an
    operator selects to stop the notifier dead. The negative half of this file uses it
    because a paused notifier is the cheapest of the three and none of those cases is
    about the notifier.
    """

    return build_trading_day_chain(
        tmp_path,
        monkeypatch,
        minute_history_parquet,
        notifier_delivery_mode="paused",
    )


@pytest.fixture
def delivery_recorder(monkeypatch: pytest.MonkeyPatch) -> _RecordingProvider:
    return confirm_deliveries_without_the_network(monkeypatch)


@pytest.fixture
def shadow_notifier_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
    delivery_recorder: _RecordingProvider,
) -> RouteAWorld:
    """The world as the production profile now builds it by default: shadow.

    The recorder is installed here for the same reason it is installed for the live world
    -- it is the provider that *can* speak. In this world it is then replaced by the
    shadow transport inside the notifier, and the case asserts it was never called.
    """

    return build_trading_day_chain(
        tmp_path,
        monkeypatch,
        minute_history_parquet,
        notifier_delivery_mode="shadow",
    )


@pytest.fixture
def active_notifier_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
    delivery_recorder: _RecordingProvider,
) -> RouteAWorld:
    """The same world sending, so the last two hops can be measured with a delivery."""

    return build_trading_day_chain(
        tmp_path,
        monkeypatch,
        minute_history_parquet,
        notifier_delivery_mode="live",
    )


RESEARCH_PLANE_DATASETS = frozenset({"lab_jobs", "promotions"})


@pytest.fixture
def research_plane_absent_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
    delivery_recorder: _RecordingProvider,
) -> RouteAWorld:
    """The chain that delivers, with the research plane exactly as the host has it.

    Neither `lab_jobs` nor `promotions` has ever published an authority generation there,
    and until #283 that alone stopped serving from cutting any generation at all.
    """

    return build_trading_day_chain(
        tmp_path,
        monkeypatch,
        minute_history_parquet,
        notifier_delivery_mode="live",
        unpublished_authorities=RESEARCH_PLANE_DATASETS,
    )


@pytest.fixture
def reference_authority_absent_chain(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    minute_history_parquet: bytes,
) -> RouteAWorld:
    """The same world with the reference plane's serving authority missing instead."""

    return build_trading_day_chain(
        tmp_path,
        monkeypatch,
        minute_history_parquet,
        unpublished_authorities=frozenset({"reference_slow_authority"}),
    )


def manifest_of(route: RouteAWorld, service_id: str) -> Any:
    return next(item for item in route.profile.manifests if item.service_id == service_id)


def setting_of(route: RouteAWorld, service_id: str, field: str) -> Path:
    return Path(str(manifest_of(route, service_id).settings[field]))


def deliver_credentials(
    route: RouteAWorld,
    root: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    """One `/run/credentials/<unit>` per credstore role, laid out as systemd lays it out.

    Root-owned 0440 `capabilities.json` admitted to the service user through an ACL, inside
    a root-owned 0550 directory on systemd's own mount -- `systemd_credential_delivery`
    moves the three facts a non-root test cannot produce and nothing else (packages E/I).
    """

    directories: dict[str, Path] = {}
    for role in sorted(CREDSTORE_ROLES):
        for instance in instance_of(route, role):
            unit = ROLE_UNITS[role]
            name = (
                f"{unit[: -len('@.service')]}@{instance}.service"
                if unit.endswith("@.service")
                else unit
            )
            delivery = deliver(
                monkeypatch,
                root=root,
                unit=name,
                payload=route.sealed_credentials[instance],
                mode=0o440,
            )
            assert delivery.path.name == RUNTIME_CAPABILITY_CREDENTIAL_NAME
            directories[instance] = delivery.directory
    return directories


@pytest.fixture
def credentials_root(
    trading_day_chain: RouteAWorld,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    return deliver_credentials(trading_day_chain, tmp_path / "credentials", monkeypatch)


@pytest.fixture
def credentials_root_shadow(
    shadow_notifier_chain: RouteAWorld,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    return deliver_credentials(shadow_notifier_chain, tmp_path / "credentials", monkeypatch)


@pytest.fixture
def credentials_root_active(
    active_notifier_chain: RouteAWorld,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    return deliver_credentials(active_notifier_chain, tmp_path / "credentials", monkeypatch)


#: One credential root per world, and never two worlds in one test: each `*_chain`
#: fixture builds its own bundle under the same `tmp_path`, so pairing a test with the
#: credentials of a different world builds the world twice and the second `mkdir` fails.
@pytest.fixture
def credentials_root_research_absent(
    research_plane_absent_chain: RouteAWorld,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    return deliver_credentials(research_plane_absent_chain, tmp_path / "credentials", monkeypatch)


@pytest.fixture
def credentials_root_reference_absent(
    reference_authority_absent_chain: RouteAWorld,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Path]:
    return deliver_credentials(
        reference_authority_absent_chain, tmp_path / "credentials", monkeypatch
    )


# ---------------------------------------------------------------------------------------
# Driving one role, at one instant, inside its own unit's sandbox
# ---------------------------------------------------------------------------------------


class Hop:
    """One role's pass, with the wall-clock cost of it."""

    def __init__(self, label: str, run: Any, seconds: float) -> None:
        self.label = label
        self.run = run
        self.seconds = seconds

    def __repr__(self) -> str:  # pragma: no cover - diagnostics only
        return f"Hop({self.label!r}, {self.seconds:.2f}s, {self.run!r})"


def run_at(
    route: RouteAWorld,
    role: str,
    *,
    instance: str,
    now: datetime,
    credentials: Path | None = None,
    label: str | None = None,
    hops: list[Hop] | None = None,
) -> Any:
    """`harness.run_role`, with the harness's frozen clock moved to `now`.

    The clock is the seventh window's `in_session` technique: `harness.FROZEN_NOW` is the
    module global the harness's registry factory closes over, so setting it moves every
    role's clock. It is set per hop rather than once, because the chain's own timing is
    part of what is under test -- the paper broker's `execution_lag_seconds` is 60, so a
    signal routed at `SESSION_NOW` is not executable at `SESSION_NOW`.
    """

    previous = harness.FROZEN_NOW
    harness.FROZEN_NOW = now
    started = time.perf_counter()
    try:
        run = harness.run_role(route, role, instance=instance, credentials=credentials)
    finally:
        harness.FROZEN_NOW = previous
    elapsed = time.perf_counter() - started
    run.heartbeat = heartbeat_of(route, role, instance)
    if hops is not None:
        hops.append(Hop(label or role, run, elapsed))
    return run


def heartbeat_of(route: RouteAWorld, role: str, instance: str) -> Any:
    """This instance's heartbeat, from the control root the wrapper's own argv names.

    `RoleRun` carries four of the heartbeat's fields and not `output_sequence`, which is
    the one that says a role *moved* rather than merely ran, so the file is re-read here.
    """

    from rquant.runtime_service_control import RuntimeServiceControl

    resolved = harness.launch(route, role, instance, None)
    argv = harness.relocated(route, list(resolved["module_argv"]))
    control_root = Path(argv[argv.index("--control-root") + 1])
    manifest = next(
        item
        for item in route.profile.manifests
        if _instance_name(item.service_id) == instance
    )
    return RuntimeServiceControl.read_heartbeat(control_root, manifest.service_spec)


# ---------------------------------------------------------------------------------------
# What the two producers in front of the chain put on disk
# ---------------------------------------------------------------------------------------


def publish_minute_batch(
    route: RouteAWorld,
    *,
    received_at: datetime = MINUTE_RECEIVED_AT,
    closes: dict[str, float] | None = None,
) -> Any:
    """One real minute batch in `live/market-minute`, through the gateway the source uses.

    `market_minute_source` fetches from Tushare and publishes through
    `MarketMinuteGateway`; this is that gateway over the same spool root the manifest
    names, so what lands on disk is byte-for-byte what the role writes. The bars are
    shaped so that `n_shape`'s four intraday inputs come out the way the evidence below
    states: the session's low stays above the candidate's rebased reference close, the
    latest close clears its rebased reference high, and the close is above the session's
    volume-weighted average price.
    """

    spool_root = setting_of(route, "feature.intraday-pit.v1", "raw_spool_root")
    resolved = closes or {code: 10.0 + index for index, code in enumerate(CODES)}

    def fetch() -> pd.DataFrame:
        rows: list[dict[str, Any]] = []
        for code, close in resolved.items():
            #: a rising session: the first bars set the low and the vwap, the last one is
            #: the breakout the evaluator reads as `latest_close`
            for step, price in enumerate((close - 0.06, close - 0.03, close)):
                stamp = datetime.combine(TRADE_DATE, clock_time(9, 45)) + timedelta(
                    minutes=step
                )
                volume = 5_000.0 + 100.0 * step
                rows.append(
                    {
                        "ts_code": code,
                        "trade_time": stamp.strftime("%Y-%m-%d %H:%M:%S"),
                        "open": round(price - 0.01, 4),
                        "high": round(price + 0.01, 4),
                        "low": round(price - 0.02, 4),
                        "close": round(price, 4),
                        "vol": volume,
                        "amount": round(volume * price, 4),
                    }
                )
        return pd.DataFrame(rows)

    gateway = MarketMinuteGateway(
        spool=LiveBatchSpool(spool_root),
        fetcher=fetch,
        config=MarketMinuteGatewayConfig(
            producer_version="market-minute-source-v1",
            producer_commit=route.world.commit,
        ),
    )
    return gateway.capture_once(received_at=received_at)


def publish_candidates(
    route: RouteAWorld,
    *,
    trade_date: date = TRADE_DATE,
    captured_at: datetime = CANDIDATES_CAPTURED_AT,
) -> tuple[Path, ...]:
    """Today's candidate documents for all three strategies, as their publishers write them.

    `candidate_publisher` assembles rows and hands them to
    `StrategyCandidateSnapshotSpool.publish_strategy_records`; this calls that writer with
    the fingerprints out of the installed manifest, which is the seam package N states and
    keeps. Package Y's `session_document` path is the producer of these rows on the host,
    and this file deliberately does not depend on that branch: what criterion (3b) is about
    is everything *downstream* of a candidate document, so the document is supplied and the
    chain behind it is real.

    `n_shape`'s static features are the ones its evaluator reads: the reference session's
    close and high rebased onto the current raw session, and the session's authoritative
    limit. They are set so that the minute batch above clears both thresholds while staying
    a full ten percent under the limit-up price.
    """

    roots: list[Path] = []
    for manifest in route.profile.manifests:
        if manifest.service_kind.value != "candidate_publisher":
            continue
        strategy_id = str(manifest.settings["strategy_id"])
        root = Path(str(manifest.settings["snapshot_root"]))
        rows = _candidate_rows(
            strategy_id=strategy_id,
            strategy_version=str(manifest.settings["strategy_version"]),
            schema=dict(manifest.settings["static_feature_schema"]),
            trade_date=trade_date,
            captured_at=captured_at,
        )
        StrategyCandidateSnapshotSpool(root).publish_strategy_records(
            strategy_id=strategy_id,
            strategy_version=str(manifest.settings["strategy_version"]),
            definition_fingerprint=str(manifest.settings["definition_fingerprint"]),
            executable_fingerprint=str(manifest.settings["executable_fingerprint"]),
            candidate_schema_fingerprint=str(
                manifest.settings["candidate_schema_fingerprint"]
            ),
            static_feature_schema=dict(manifest.settings["static_feature_schema"]),
            source_snapshot_ids={"candidate_input": "1" * 64},
            trade_date=trade_date,
            captured_at=captured_at,
            producer_commit=manifest.producer_commit,
            rows=rows,
        )
        roots.append(root)
    assert roots
    return tuple(roots)


def _candidate_rows(
    *,
    strategy_id: str,
    strategy_version: str,
    schema: dict[str, Any],
    trade_date: date,
    captured_at: datetime,
) -> tuple[StrategyCandidateRecord, ...]:
    """One candidate per strategy, carrying exactly the static features its schema names."""

    #: `n_shape`'s thresholds, against a minute batch whose last close for `SIGNAL_CODE`
    #: is 11.0 and whose session low is 10.92 (see `publish_minute_batch`).
    values: dict[str, Any] = {
        #: `_raw_session_basis` requires exactly this string. It is not the record's
        #: `price_basis` (`raw` / `qfq_pit`, which is how the *reference* prices were
        #: adjusted) but a statement about the three prices beside it: they have been
        #: rebased onto the current session's raw quotes, so comparing them against an
        #: unadjusted intraday close is sound.
        "candidate_price_basis": "raw_session",
        "t_close_session_raw": 10.5,
        "t_high_session_raw": 10.8,
        "limit_up_price_session_raw": 12.1,
        "limit_pct": 10.0,
    }
    #: `growth_board_surge` and `auction_gap` declare their own static features, and their
    #: signals are not what this file is about. Anything their schema names and the map
    #: above does not is filled with a neutral value **of the dtype the schema declares**:
    #: `publish_strategy_records` type-checks every static feature against it, so a filler
    #: that guessed `float` for `ma_alignment` (declared `bool`) is refused by the writer.
    neutral: dict[str, Any] = {
        "number": 1.0,
        "integer": 1,
        "string": "raw_session_only",
        "bool": True,
        "null": None,
    }
    static: dict[str, Any] = {}
    for name, spec in schema.items():
        if name in values:
            static[name] = values[name]
            continue
        dtype = str(dict(spec).get("dtype"))
        assert dtype in neutral, f"no neutral value for {name!r} of dtype {dtype!r}"
        static[name] = neutral[dtype]
    decision_at = captured_at - timedelta(minutes=17)
    return (
        StrategyCandidateRecord(
            strategy_id=strategy_id,
            strategy_version=strategy_version,
            candidate_id=SIGNAL_CODE,
            variant="default",
            decision_at=decision_at,
            available_at=decision_at + timedelta(minutes=3),
            effective_trade_date=trade_date,
            reference_trade_date=OPEN_DATES[-2],
            price_basis=StrategyCandidatePriceBasis.QFQ_PIT,
            static_features=static,
            reference_snapshot_ids={"daily": "8" * 64},
        ),
    )


# ---------------------------------------------------------------------------------------
# Reading each hop's artifact
# ---------------------------------------------------------------------------------------


def feature_batches(route: RouteAWorld) -> int:
    """The feature spool's published high watermark, read the way a consumer reads it.

    A read-only consumer has to bring its own cursor root from outside the producer's
    directory (#231), so this reader brings one too rather than reaching for the default
    that sits inside `live/features`.
    """

    from rquant.feature_spool import FeatureBatchSpool

    root = setting_of(route, "feature.intraday-pit.v1", "feature_spool_root")
    #: `install_runtime_deployment_bundle` creates `live/features` empty and the feature
    #: role's own builder is what turns it into a spool, so "no `batches/` yet" is the
    #: pre-role state rather than a damaged store
    if not (root / "batches").is_dir():
        return -1
    cursors = route.runtime_root.parent / "test-feature-cursors"
    return (
        FeatureBatchSpool(root, read_only=True, cursor_root=cursors)
        .source_descriptor()
        .high_watermark
    )


def runner_signal_count(route: RouteAWorld, service_id: str) -> int:
    path = setting_of(route, service_id, "runner_state_path")
    if not path.is_file():
        return 0
    with closing(sqlite3.connect(f"file:{path}?mode=ro", uri=True)) as connection:
        return int(connection.execute("SELECT count(*) FROM runner_signal").fetchone()[0])


def _row_counts(path: Path, tables: tuple[str, ...]) -> dict[str, int]:
    """Row counts for `tables`, reading the store the way a bystander reads it.

    Read-only URI mode rather than a plain `connect`, because a plain connect on a WAL
    database creates the `-shm` wal-index beside it, which is the write into a producer's
    directory the all-roles file records as `KNOWN_C_LEVEL_WRITES`. A reader in a test
    should not add another one.
    """

    if not path.is_file():
        return dict.fromkeys(tables, 0)
    counts: dict[str, int] = {}
    with closing(sqlite3.connect(f"file:{path}?mode=ro", uri=True)) as connection:
        present = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'"
            )
        }
        for table in tables:
            counts[table] = (
                int(connection.execute(f"SELECT count(*) FROM {table}").fetchone()[0])
                if table in present
                else 0
            )
    return counts


def signal_bus_counts(route: RouteAWorld) -> dict[str, int]:
    """What the router left on the bus: envelopes, route receipts, and the outbox rows."""

    return _row_counts(
        setting_of(route, "signal-router.all-strategies.v1", "signal_bus_path"),
        ("signal_envelope", "signal_route_receipt", "delivery_outbox", "delivery_attempt"),
    )


def paper_fill_count(route: RouteAWorld) -> int:
    """Fills in the paper broker's own ledger -- the hop that books a routed signal."""

    return _row_counts(
        setting_of(route, "paper-broker.shadow-main.v1", "broker_path"),
        ("paper_fill",),
    )["paper_fill"]


def notification_counts(route: RouteAWorld) -> dict[str, int]:
    """The notifier's own durable outbox, replicated from the route spool.

    `NotificationStateStore` extends `SignalBusStore`, so the notifier's store carries its
    own `delivery_outbox` / `delivery_attempt` beside the replication tables. These are
    the rows criterion (3b) means by "the notifier produced a notification": they are in
    the notifier's database, not the router's.
    """

    return _row_counts(
        setting_of(route, "notifier.admin.shadow.v1", "notification_state_path"),
        (
            "notification_replication_source",
            "notification_source_route_receipt",
            "signal_envelope",
            "delivery_outbox",
            "delivery_attempt",
        ),
    )


def notification_attempt_receipts(route: RouteAWorld) -> tuple[str, ...]:
    """Every provider receipt the notifier's own attempt log holds.

    `shadow:` in front of each of them is one of the two marks of a shadow notifier (the
    other is `notifier:shadow_transport` on the heartbeat), and the mark is what tells a
    later reader of this database that those deliveries never left the host.
    """

    path = setting_of(route, "notifier.admin.shadow.v1", "notification_state_path")
    if not path.is_file():
        return ()
    with closing(sqlite3.connect(f"file:{path}?mode=ro", uri=True)) as connection:
        return tuple(
            str(row[0])
            for row in connection.execute(
                "SELECT provider_receipt FROM delivery_attempt WHERE provider_receipt IS NOT NULL"
            )
        )


def serving_generations(route: RouteAWorld) -> tuple[Path, ...]:
    root = setting_of(route, "serving.publisher.v1", "serving_root") / "generations"
    if not root.is_dir():
        return ()
    return tuple(sorted(path for path in root.iterdir() if path.is_dir()))


def serving_current(route: RouteAWorld) -> dict[str, Any] | None:
    pointer = setting_of(route, "serving.publisher.v1", "serving_root") / "current.json"
    if not pointer.is_file():
        return None
    return json.loads(pointer.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------------------
# The chain
# ---------------------------------------------------------------------------------------


def test_the_world_is_two_generations_on_a_session_the_calendar_opens(
    trading_day_chain: RouteAWorld,
) -> None:
    """The premise, asserted before anything is asserted about the roles."""

    generations = sorted(
        path.name
        for path in (trading_day_chain.runtime_root / "generations").iterdir()
        if path.is_dir()
    )
    assert len(generations) == 2, generations
    assert trading_day_chain.receipt.previous_generation_hash in generations
    assert trading_day_chain.receipt.generation_hash in generations

    #: the sealed history the profile records is the real export, not the placeholder
    snapshot = setting_of(
        trading_day_chain, "feature.intraday-pit.v1", "historical_minutes_snapshot_path"
    )
    recorded = str(
        manifest_of(trading_day_chain, "feature.intraday-pit.v1").settings[
            "historical_snapshot_id"
        ]
    )
    assert hashlib.sha256(snapshot.read_bytes()).hexdigest() == recorded
    assert snapshot.stat().st_size > 1_000, "the installed history is still a placeholder"

    #: and the clock this file runs at is a session the bundle's own calendar opens
    from rquant.runtime_market_session import load_market_calendar_authority

    calendar_path = setting_of(trading_day_chain, N_SHAPE_SERVICE_ID, "calendar_path")
    calendar = load_market_calendar_authority(
        calendar_path,
        expected_commit=str(
            manifest_of(trading_day_chain, N_SHAPE_SERVICE_ID).settings[
                "calendar_expected_commit"
            ]
        ),
    )
    assert calendar.content_sha256 == str(
        manifest_of(trading_day_chain, N_SHAPE_SERVICE_ID).settings["calendar_content_sha256"]
    )
    assert TRADE_DATE in calendar.open_dates
    assert set(OPEN_DATES) <= set(calendar.open_dates)
    assert SESSION_NOW.astimezone(_SHANGHAI).date() == TRADE_DATE


def test_the_feature_role_turns_a_minute_batch_into_a_feature_batch(
    trading_day_chain: RouteAWorld,
) -> None:
    """The first hop, and the one no world in this repository could take before.

    `feature_live` hashes the sealed history at start-up and refuses a mismatch, then
    joins it to whatever `market_minute_source` has published. With a zero-row history it
    could start; with a zero-row *spool* it had nothing to do. This is both halves real.
    """

    assert feature_batches(trading_day_chain) == -1
    capture = publish_minute_batch(trading_day_chain)
    assert capture.published is True

    instance = instance_of(trading_day_chain, FEATURE_ROLE)[0]
    run = run_at(trading_day_chain, FEATURE_ROLE, instance=instance, now=SESSION_NOW)

    assert run.refusal is None, run.traceback
    assert run.entered, run
    assert run.violations == [], run.violations
    assert run.exit_code == 0
    assert feature_batches(trading_day_chain) >= 0, "the feature role published nothing"


def test_the_n_shape_strategy_emits_a_signal_from_a_real_feature_batch(
    trading_day_chain: RouteAWorld,
) -> None:
    """The second hop: a candidate universe plus a feature batch becomes a signal.

    `n_shape` is the simplest of the three evaluators -- carry, breakout, vwap, below the
    limit -- and every one of those four reads comes from somewhere real here: the three
    session values out of the feature batch the previous hop produced, and the rebased
    reference close, reference high and limit-up price out of the candidate document.
    """

    publish_minute_batch(trading_day_chain)
    publish_candidates(trading_day_chain)
    feature = instance_of(trading_day_chain, FEATURE_ROLE)[0]
    run_at(trading_day_chain, FEATURE_ROLE, instance=feature, now=SESSION_NOW)

    instance = _instance_name(N_SHAPE_SERVICE_ID)
    assert runner_signal_count(trading_day_chain, N_SHAPE_SERVICE_ID) == 0
    run = run_at(trading_day_chain, STRATEGY_ROLE, instance=instance, now=SESSION_NOW)

    assert run.refusal is None, run.traceback
    assert run.entered, run
    assert run.violations == [], run.violations
    assert run.last_error is None, run.last_error
    assert runner_signal_count(trading_day_chain, N_SHAPE_SERVICE_ID) >= 1, (
        "the strategy consumed the feature batch and emitted nothing"
    )


#: The chain, in the runbook's C-3 order, with the producers each hop needs in front of
#: it. `paper_constraint_publisher` is what puts a current pointer under
#: `authorities/paper-execution`, which package J recorded as the one thing an otherwise
#: healthy paper broker waits on, and `runtime_health_publisher` owns one of the six
#: source authorities serving reads.
#:
#: `reference_slow_source` and `reference_slow_publisher` are deliberately **not** here.
#: They are pre-open roles -- the publisher refuses outright after 09:25 -- and their
#: product, one published reference generation, is an *input* to this chain rather than a
#: hop of it, so it is written by the same writer they use and the session starts with it
#: already on disk, exactly as a host that ran them at 09:0x would have.
CHAIN_ORDER: tuple[tuple[str, str], ...] = (
    ("runtime_health_publisher", "health"),
    ("paper_constraint_publisher", "constraint"),
    ("feature_live", "feature"),
    ("strategy_live", "strategy"),
    ("signal_router", "router"),
    ("paper_broker", "broker"),
    ("notifier", "notifier"),
    ("serving_publisher", "serving"),
)

#: when each role in `CHAIN_ORDER` runs. The chain's own timing is under test, so these
#: are not one instant: the paper broker's `execution_lag_seconds` is 60, so a signal
#: routed at `SESSION_NOW` is not executable until the minute after.
HOP_CLOCKS: dict[str, datetime] = {
    "runtime_health_publisher": _at(9, 47, 17),
    "paper_constraint_publisher": _at(9, 47, 29),
    "feature_live": SESSION_NOW,
    "strategy_live": _at(9, 47, 51),
    "signal_router": ROUTER_NOW,
    "paper_broker": BROKER_NOW,
    "notifier": NOTIFIER_NOW,
    "serving_publisher": SERVING_NOW,
}


def drive_the_chain(
    route: RouteAWorld,
    credentials: dict[str, Path],
    *,
    hops: list[Hop],
    roles: tuple[tuple[str, str], ...] = CHAIN_ORDER,
) -> dict[str, list[Any]]:
    """Every role in `CHAIN_ORDER`, each at its own instant, inside its own unit."""

    runs: dict[str, list[Any]] = {}
    for role, label in roles:
        for instance in instance_of(route, role):
            run = run_at(
                route,
                role,
                instance=instance,
                now=HOP_CLOCKS[role],
                credentials=credentials.get(instance),
                label=label,
                hops=hops,
            )
            runs.setdefault(role, []).append(run)
    return runs


def bus_envelopes_for(route: RouteAWorld, strategy_id: str) -> int:
    """Envelopes on the signal bus that came from one strategy."""

    path = setting_of(route, "signal-router.all-strategies.v1", "signal_bus_path")
    if not path.is_file():
        return 0
    with closing(sqlite3.connect(f"file:{path}?mode=ro", uri=True)) as connection:
        columns = {
            str(row[1]) for row in connection.execute("PRAGMA table_info(signal_envelope)")
        }
        column = next(
            name for name in ("signal_json", "payload_json", "envelope_json") if name in columns
        )
        return int(
            connection.execute(
                f"SELECT count(*) FROM signal_envelope WHERE {column} LIKE ?",
                (f'%"strategy_id":"{strategy_id}"%',),
            ).fetchone()[0]
        )


def tamper_one_byte_of_a_runner_signal(route: RouteAWorld, service_id: str) -> None:
    """Flip one byte of one stored signal payload in a strategy's runner database.

    A single byte inside the JSON payload, not a structural edit: the row still parses and
    still has every field, so what refuses it downstream can only be the integrity check
    rather than a shape check that would have refused a malformed row anyway.
    """

    path = setting_of(route, service_id, "runner_state_path")
    with closing(sqlite3.connect(path)) as connection:
        connection.row_factory = sqlite3.Row
        columns = {
            str(row["name"])
            for row in connection.execute("PRAGMA table_info(runner_signal)")
        }
        column = next(
            name for name in ("signal_json", "payload_json", "envelope_json") if name in columns
        )
        #: `sequence` is `INTEGER PRIMARY KEY`, so it *is* the rowid and the result
        #: column carries that name rather than "rowid"
        row = connection.execute(
            f"SELECT sequence, {column} AS payload FROM runner_signal "
            "ORDER BY sequence LIMIT 1"
        ).fetchone()
        assert row is not None, "there is no runner signal to tamper with"
        payload = str(row["payload"])
        #: the last digit of the first price-like number, so the document stays valid JSON
        index = payload.index('"latest_close":') + len('"latest_close":')
        flipped = payload[:index] + ("8" if payload[index] != "8" else "7") + payload[index + 1 :]
        assert flipped != payload
        connection.execute(
            f"UPDATE runner_signal SET {column} = ? WHERE sequence = ?",
            (flipped, row["sequence"]),
        )
        connection.commit()


def serving_signal_rows(route: RouteAWorld, *, session: date | None = TRADE_DATE) -> int:
    """Rows in the `signals` table of the generation `current.json` points at.

    **Scoped to one session by default, and that is the point.** The notifier publishes
    the newest `serving_history_limit` route receipts (default 1000,
    `runtime_builder_signal.NotifierSettings.serving_history_limit`) selected by
    `ORDER BY signal.global_sequence DESC LIMIT ?` with no date predicate at all
    (`notification_state.py`). So `signals` is a rolling history, not a same-day table:
    once one signal has ever been published, an unfiltered `count(*)` is greater than zero
    every day afterwards, including a day on which nothing traded.

    Criterion (3b) is a claim about *today*, so the count it is read from has to be
    filtered by `event_time`, which is one of the table's own columns
    (`serving_read_models.build_serving_read_models`). `session=None` gives the unfiltered
    count, which is only useful for saying how much history a generation carries.
    """

    from rquant.serving_publisher import ServingReader

    root = setting_of(route, "serving.publisher.v1", "serving_root")
    with ServingReader(root).open_current_readonly() as connection:
        total = int(connection.execute("SELECT count(*) FROM signals").fetchone()[0])
        if session is None or total == 0:
            #: An empty generation cannot be filtered by time: the table is built from an
            #: empty frame, so DuckDB has no rows to infer from and types `event_time`
            #: `INTEGER` rather than `TIMESTAMP WITH TIME ZONE`, and comparing it with an
            #: instant is a binder error. Zero rows in total is zero rows in any session.
            #:
            #: **This guard is load-bearing, not an optimisation.** Delete it and
            #: `test_the_paused_notifier_stops_the_signal_at_the_paper_broker` fails with
            #: `Binder Error: Cannot compare values of type INTEGER and type TIMESTAMP
            #: WITH TIME ZONE`, because a paused notifier is exactly the case that leaves
            #: this table empty. The operator command in the package report spells the
            #: same rule `TRY_CAST(event_time AS TIMESTAMPTZ)` for the same reason.
            return total
        #: the session opens at 09:15 local, before the auction, so the bound catches
        #: everything the day produced and nothing the day before did
        opened_at = datetime.combine(
            session, clock_time(9, 15), tzinfo=_SHANGHAI
        ).astimezone(UTC)
        #: an explicit TIMESTAMPTZ literal rather than a bound parameter: the reader's
        #: connection binds a Python datetime as an integer and DuckDB then refuses to
        #: compare it with the column's own type
        return int(
            connection.execute(
                "SELECT count(*) FROM signals "
                f"WHERE event_time >= TIMESTAMPTZ '{opened_at.isoformat()}'"
            ).fetchone()[0]
        )


def _print_hops(capsys: pytest.CaptureFixture[str], hops: list[Hop]) -> None:
    with capsys.disabled():
        print("\n  hop timings (wall clock, one pass each)")
        for hop in hops:
            print(
                f"    {hop.label:<12} {hop.seconds:6.2f}s  status={hop.run.status}"
                f" seq={getattr(hop.run.heartbeat, 'output_sequence', None)}"
                f" error={hop.run.last_error}"
            )


def _assert_every_role_stayed_inside_its_unit(hops: list[Hop]) -> None:
    outside = {
        hop.label: [violation.path for violation in hop.run.violations]
        for hop in hops
        if hop.run.violations
    }
    assert outside == {}, outside
    refused = {hop.label: hop.run.traceback for hop in hops if hop.run.refusal is not None}
    assert refused == {}, refused
    stalled = [hop.label for hop in hops if not hop.run.entered]
    assert stalled == [], stalled
    failed = {hop.label: hop.run.last_error for hop in hops if hop.run.last_error}
    assert failed == {}, failed


def test_one_signal_travels_the_whole_chain_to_a_same_day_serving_generation(
    active_notifier_chain: RouteAWorld,
    credentials_root_active: dict[str, Path],
    delivery_recorder: _RecordingProvider,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion (3b), end to end, with every hop's artifact asserted on disk.

    The two producers in front of the chain put a minute batch and today's candidate
    documents where their owners would have put them; from there every hop is the real
    role, built by the real builder out of the real manifest, inside the sandbox its own
    unit describes. Every assertion below is about what that role left behind.

    The notifier is `live` here, which is one value of one input (#281), and the two cases
    after this one run the identical world on the other two: `shadow`, which is what the
    profile now builds by default, and `paused`, the emergency stop. The three differ by
    that value and nothing else, so a difference between them is a difference the mode
    makes.
    """

    route = active_notifier_chain
    capture = publish_minute_batch(route)
    assert capture.published is True
    publish_candidates(route)

    before = feature_batches(route)
    assert before == -1, "the feature spool already had a batch before the chain ran"

    hops: list[Hop] = []
    drive_the_chain(route, credentials_root_active, hops=hops)
    _print_hops(capsys, hops)
    _assert_every_role_stayed_inside_its_unit(hops)

    by_label = {hop.label: hop.run for hop in hops}

    # -- hop 1: a minute batch became a feature batch -----------------------------------
    assert feature_batches(route) >= 0, "the feature role published nothing"
    assert by_label["feature"].heartbeat.output_sequence == feature_batches(route)

    # -- hop 2: a feature batch and today's candidate became a signal -------------------
    assert runner_signal_count(route, N_SHAPE_SERVICE_ID) >= 1, (
        "the strategy consumed the feature batch and emitted nothing"
    )

    # -- hop 3: the router put it on the bus and in the route spool ---------------------
    counts = signal_bus_counts(route)
    assert counts["signal_envelope"] >= 1, counts
    assert counts["signal_route_receipt"] >= 1, counts
    assert counts["delivery_outbox"] >= 1, counts
    spool_root = setting_of(route, "signal-router.all-strategies.v1", "signal_spool_root")
    assert (spool_root / "source.json").is_file()
    assert by_label["router"].heartbeat.output_sequence >= 1

    # -- hop 4: the paper broker booked it ----------------------------------------------
    assert paper_fill_count(route) >= 1, "the paper broker booked nothing"

    # -- hop 5: the notifier replicated it and delivered it -----------------------------
    notifications = notification_counts(route)
    assert notifications["delivery_outbox"] >= 1, notifications
    assert notifications["delivery_attempt"] >= 1, notifications
    assert notifications["notification_source_route_receipt"] >= 1, notifications
    assert delivery_recorder.deliveries, "no delivery reached a provider"
    assert by_label["notifier"].heartbeat.degraded_reasons == (), (
        by_label["notifier"].heartbeat.degraded_reasons
    )

    # -- hop 6: serving published a same-day generation carrying the signal -------------
    generations = serving_generations(route)
    assert len(generations) == 1, generations
    pointer = serving_current(route)
    assert pointer is not None
    assert pointer["generation_id"] == generations[0].name
    assert (generations[0] / "serving.duckdb").is_file()
    #: the criterion, session-scoped: a rolling-history table answers "has one ever been
    #: published", and (3b) asks "did one travel today"
    assert serving_signal_rows(route, session=TRADE_DATE) >= 1, (
        "serving published a generation that carries no signal for this session"
    )


#: What an authority root that exists but holds no generation answers. The research
#: roots are pre-created on the host (runbook C-1), so this is the refusal serving
#: actually sees there -- "current authority is unavailable" is the other one, for a root
#: that was never created at all.
UNAVAILABLE_AUTHORITY_REASON = (
    "ServingSourceAuthorityUnavailableError: current pointer is unavailable"
)


def test_the_chain_reaches_serving_with_the_research_plane_never_published(
    research_plane_absent_chain: RouteAWorld,
    credentials_root_research_absent: dict[str, Path],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Criterion (3b) on the host as it really is, research plane and all (#283).

    Two of serving's six source authorities belong to roles that have never run here:
    `research/serving-authorities/lab-jobs` and `.../promotions` hold no generation, and
    while all six reads were fail-closed that absence cost the whole round -- not one
    generation was cut, on a day every hop of the signal chain worked.

    What is asserted is that the two halves hold at once: serving publishes the same-day
    generation and the signal is in it, **and** the heartbeat says out loud which two
    sources it did not have. An operator reading 5.5 of the acceptance list sees the
    difference between "the research plane has not started" and "the signal chain is
    broken" without opening anything else.
    """

    route = research_plane_absent_chain
    assert publish_minute_batch(route).published is True
    publish_candidates(route)

    hops: list[Hop] = []
    drive_the_chain(route, credentials_root_research_absent, hops=hops)
    _print_hops(capsys, hops)
    _assert_every_role_stayed_inside_its_unit(hops)

    serving = next(hop.run for hop in hops if hop.label == "serving")

    #: serving published, and the signal that travelled today is in what it published
    assert len(serving_generations(route)) == 1, serving_generations(route)
    assert serving_current(route) is not None
    assert serving_signal_rows(route, session=TRADE_DATE) >= 1, (
        "serving cut a generation that carries no signal for this session"
    )

    #: and the absence is on the heartbeat, named source by source. The list is filtered
    #: rather than compared whole: this world degrades serving on other counts too (the
    #: runtime health projection names the roles that have no heartbeat yet), and what
    #: (3b) is read from is which *sources* were missing.
    reasons = tuple(serving.heartbeat.degraded_reasons)
    assert sorted(
        reason
        for reason in reasons
        if reason.startswith(("serving:lab_jobs:", "serving:promotions:"))
    ) == [
        f"serving:lab_jobs:unavailable:{UNAVAILABLE_AUTHORITY_REASON}",
        f"serving:promotions:unavailable:{UNAVAILABLE_AUTHORITY_REASON}",
    ], reasons
    #: and no source outside the research plane was degraded into silence
    assert [reason for reason in reasons if reason.startswith("serving:signals:")] == [], reasons
    #: degraded, which is a role that ran, and not failed. `run.status` is what the
    #: instance ended on (`stopped`, since the harness runs one pass and stops it), so
    #: the distinction is read from the heartbeat the pass wrote.
    assert serving.heartbeat.last_error is None, serving.heartbeat.last_error
    assert serving.heartbeat.consecutive_failures == 0
    assert serving.heartbeat.total_successes >= 1
    assert serving.heartbeat.last_success_at is not None


def test_serving_still_refuses_the_round_without_the_reference_authority(
    reference_authority_absent_chain: RouteAWorld,
    credentials_root_reference_absent: dict[str, Path],
) -> None:
    """The first negative of #283: `reference_slow` is not one of the optional two.

    Its payload is the only source payload with no legal empty value -- the reference
    generation id, the revision, and the price and adjustment basis a serving row is
    quoted on are all required -- so degrading it could only mean publishing an invented
    basis. The round stops instead, and nothing is selected.
    """

    route = reference_authority_absent_chain
    publish_minute_batch(route)
    publish_candidates(route)

    hops: list[Hop] = []
    drive_the_chain(route, credentials_root_reference_absent, hops=hops)
    serving = next(hop.run for hop in hops if hop.label == "serving")

    assert serving.last_error is not None
    assert "reference_slow_authority reader failed" in serving.last_error, serving.last_error
    assert serving_generations(route) == (), serving_generations(route)
    assert serving_current(route) is None


def test_serving_still_refuses_the_round_without_the_signals_authority(
    trading_day_chain: RouteAWorld,
    credentials_root: dict[str, Path],
) -> None:
    """The second negative, and the one criterion (3b) depends on.

    The notifier owns the `signals` authority, so the chain is driven without it and the
    authority is never written. If `signals` degraded the way the research sources do,
    serving would publish a generation with an empty `signals` table -- byte for byte the
    same thing it publishes on a day that really produced no signal -- and (3b) would
    stop being able to tell "nothing traded today" from "the notifier is broken".
    """

    route = trading_day_chain
    publish_minute_batch(route)
    publish_candidates(route)

    without_the_notifier = tuple(entry for entry in CHAIN_ORDER if entry[0] != "notifier")
    assert len(without_the_notifier) == len(CHAIN_ORDER) - 1
    hops: list[Hop] = []
    drive_the_chain(route, credentials_root, hops=hops, roles=without_the_notifier)
    serving = next(hop.run for hop in hops if hop.label == "serving")

    assert serving.last_error is not None
    assert "signals reader failed" in serving.last_error, serving.last_error
    assert serving_generations(route) == (), serving_generations(route)
    assert serving_current(route) is None


def test_the_shadow_mode_notifier_writes_every_row_and_sends_nothing(
    shadow_notifier_chain: RouteAWorld,
    credentials_root_shadow: dict[str, Path],
    delivery_recorder: _RecordingProvider,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """#281 shadow: the same chain as the live case, with nothing on the wire.

    This is the profile's default, so it is the answer to "what does the host do on
    2026-09-23 if nobody changes anything". Every row the live case produces is produced
    here -- the route receipts replicated into the notifier's own store, the outbox rows,
    the leased attempts, a `signals` serving authority carrying this session's signal --
    and the one thing that does not happen is the send.

    The recorder is the provider that can speak, installed by the same fixture the live
    case uses, and it is asserted empty: not "the transport was configured away" but "the
    thing that would have talked was never called". The heartbeat says
    `notifier:shadow_transport`, so no operator reading it can mistake this for a live
    notifier that happened to have nothing to deliver.

    The `signals` assertion is filtered by `event_time` rather than counted (MF-3): the
    authority carries a rolling history, so a non-empty table alone would not say that
    today's signal is in it.
    """

    route = shadow_notifier_chain
    assert manifest_of(route, "notifier.admin.shadow.v1").settings["suppress_delivery"] is True
    assert manifest_of(route, "notifier.admin.shadow.v1").settings["paused"] is False

    publish_minute_batch(route)
    publish_candidates(route)

    hops: list[Hop] = []
    drive_the_chain(route, credentials_root_shadow, hops=hops)
    _print_hops(capsys, hops)
    _assert_every_role_stayed_inside_its_unit(hops)

    #: the first four hops are the live ones
    assert runner_signal_count(route, N_SHAPE_SERVICE_ID) >= 1
    assert signal_bus_counts(route)["signal_envelope"] >= 1
    assert paper_fill_count(route) >= 1

    #: the notifier did all of its work
    notifications = notification_counts(route)
    assert notifications["notification_source_route_receipt"] >= 1, notifications
    assert notifications["delivery_outbox"] >= 1, notifications
    assert notifications["delivery_attempt"] >= 1, notifications

    #: and none of it reached a provider that could have spoken
    assert delivery_recorder.deliveries == [], delivery_recorder.deliveries

    notifier = next(hop.run for hop in hops if hop.label == "notifier")
    assert "notifier:shadow_transport" in (notifier.heartbeat.degraded_reasons or ()), (
        notifier.heartbeat.degraded_reasons
    )
    assert "notifier:paused" not in (notifier.heartbeat.degraded_reasons or ())

    #: every receipt in the attempt log is a shadow receipt
    receipts = notification_attempt_receipts(route)
    assert receipts, "the notifier claimed nothing"
    assert all(receipt.startswith("shadow:") for receipt in receipts), receipts

    #: and serving published this session's signal
    assert len(serving_generations(route)) == 1
    assert serving_current(route) is not None
    assert serving_signal_rows(route, session=TRADE_DATE) >= 1, (
        "the shadow notifier published a generation with no signal from this session"
    )


def test_the_paused_notifier_stops_the_signal_at_the_paper_broker(
    trading_day_chain: RouteAWorld,
    credentials_root: dict[str, Path],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """`notifier_delivery_mode="paused"`: the emergency stop, measured.

    This was the shipped behaviour until #281 made the mode an input, and it is what an
    operator now selects deliberately. The first four hops are identical -- the signal is
    emitted, routed, and booked -- and then the notifier, being paused, replicates
    nothing, writes no outbox row, and publishes a `signals` serving authority built from
    its own empty store. Serving still cuts a generation, because five of its six sources
    moved, and that generation carries **no signal**.

    So "a generation appears under `serving/generations/`" is true with the notifier
    stopped and "one signal travels the chain to serving" is not. Asserted rather than
    described, so the day the emergency stop stops stopping things, this case says so.
    """

    route = trading_day_chain
    assert manifest_of(route, "notifier.admin.shadow.v1").settings["paused"] is True
    assert manifest_of(route, "notifier.admin.shadow.v1").settings["suppress_delivery"] is False

    publish_minute_batch(route)
    publish_candidates(route)

    hops: list[Hop] = []
    drive_the_chain(route, credentials_root, hops=hops)
    _print_hops(capsys, hops)
    _assert_every_role_stayed_inside_its_unit(hops)

    #: the first four hops are the same
    assert runner_signal_count(route, N_SHAPE_SERVICE_ID) >= 1
    assert signal_bus_counts(route)["signal_envelope"] >= 1
    assert paper_fill_count(route) >= 1

    #: and the notifier, paused, produced nothing at all
    notifications = notification_counts(route)
    assert notifications["delivery_outbox"] == 0, notifications
    assert notifications["delivery_attempt"] == 0, notifications
    assert notifications["notification_source_route_receipt"] == 0, notifications
    notifier = next(hop.run for hop in hops if hop.label == "notifier")
    assert "notifier:paused" in (notifier.heartbeat.degraded_reasons or ()), (
        notifier.heartbeat.degraded_reasons
    )
    assert "notifier:shadow_transport" not in (notifier.heartbeat.degraded_reasons or ())

    #: serving published, and what it published has no signal in it
    assert len(serving_generations(route)) == 1
    assert serving_current(route) is not None
    assert serving_signal_rows(route, session=TRADE_DATE) == 0
    #: and it is not that the history was trimmed -- there is nothing in it at all
    assert serving_signal_rows(route, session=None) == 0


# ---------------------------------------------------------------------------------------
# The negative half
# ---------------------------------------------------------------------------------------


def test_a_candidate_document_dated_anything_but_today_is_refused_by_the_loader(
    trading_day_chain: RouteAWorld,
) -> None:
    """Criterion (3a)'s guard, from the strategy's side of it.

    `run_strategy_live_batch` derives `required_trade_date` from the feature envelope's
    own event time, so the date a candidate document has to carry is not a parameter the
    role can drift on: it is the session the features came from.
    `RuntimeCandidateUniverseLoader._validate_snapshot` compares it twice, once for the
    snapshot and once for every row, and refuses either way.

    The document here is yesterday's -- a publisher that did not run this morning, which
    is exactly the 2026-09-21 shape package Y was about -- and the strategy refuses rather
    than trading on it.
    """

    publish_minute_batch(trading_day_chain)
    publish_candidates(
        trading_day_chain,
        trade_date=OPEN_DATES[-2],
        captured_at=CANDIDATES_CAPTURED_AT - timedelta(days=1),
    )
    feature = instance_of(trading_day_chain, FEATURE_ROLE)[0]
    run_at(trading_day_chain, FEATURE_ROLE, instance=feature, now=HOP_CLOCKS[FEATURE_ROLE])

    instance = _instance_name(N_SHAPE_SERVICE_ID)
    run = run_at(
        trading_day_chain,
        STRATEGY_ROLE,
        instance=instance,
        now=HOP_CLOCKS[STRATEGY_ROLE],
    )

    #: fail-closed and visible: the role stays up, the iteration does not, and the
    #: heartbeat says which check refused
    assert run.entered, run
    assert run.violations == [], run.violations
    assert "trade date does not match required trade date" in (run.last_error or ""), (
        run.last_error
    )
    assert runner_signal_count(trading_day_chain, N_SHAPE_SERVICE_ID) == 0


def test_a_signal_receipt_with_one_byte_changed_is_refused_by_the_router(
    trading_day_chain: RouteAWorld,
) -> None:
    """The router's integrity check, against a runner store altered by a single byte.

    The strategy signs what it emits and the router verifies it before routing, so a
    runner database edited underneath the pair is the tamper this checks. One byte of one
    signal's stored payload is flipped -- the row is still well-formed SQL and still
    parses -- and the router refuses to route it rather than degrading past it.
    """

    publish_minute_batch(trading_day_chain)
    publish_candidates(trading_day_chain)
    feature = instance_of(trading_day_chain, FEATURE_ROLE)[0]
    run_at(trading_day_chain, FEATURE_ROLE, instance=feature, now=HOP_CLOCKS[FEATURE_ROLE])
    #: all three, because the router refuses to start on a missing runner source and
    #: would otherwise stop on `auction_gap`'s absence rather than on the tamper (#232)
    for strategy in instance_of(trading_day_chain, STRATEGY_ROLE):
        run_at(
            trading_day_chain,
            STRATEGY_ROLE,
            instance=strategy,
            now=HOP_CLOCKS[STRATEGY_ROLE],
        )
    assert runner_signal_count(trading_day_chain, N_SHAPE_SERVICE_ID) >= 1

    tamper_one_byte_of_a_runner_signal(trading_day_chain, N_SHAPE_SERVICE_ID)

    router = instance_of(trading_day_chain, ROUTER_ROLE)[0]
    run = run_at(trading_day_chain, ROUTER_ROLE, instance=router, now=HOP_CLOCKS[ROUTER_ROLE])

    assert run.entered, run
    assert run.violations == [], run.violations
    assert run.last_error is not None, "the router routed a tampered signal"
    #: The refusal is an integrity refusal, not a shape or a timing one: `signal_id` is a
    #: digest of the payload, so a payload that no longer hashes to the id it is stored
    #: under cannot be parsed back into the signal it claims to be. This is the fail-closed
    #: rule the package Y review states -- a tamper must still raise, and only report-shape
    #: or timing conditions may degrade -- so the message is asserted verbatim rather than
    #: matched loosely, and a future change that turns this into a degradation fails here.
    assert "runner signal payload is invalid" in run.last_error, run.last_error
    #: and the tampered source put nothing on the bus. The router works per source, so
    #: `auction_gap`'s own (untampered) watch signal is routed in the same iteration --
    #: refusing one source's ledger is not a reason to drop another's -- and what must be
    #: absent is every envelope from the strategy whose store was edited.
    assert bus_envelopes_for(trading_day_chain, "n_shape") == 0
    assert bus_envelopes_for(trading_day_chain, "auction_gap") >= 1


def test_serving_does_not_cut_a_second_generation_for_content_that_has_not_moved(
    active_notifier_chain: RouteAWorld,
    credentials_root_active: dict[str, Path],
    delivery_recorder: _RecordingProvider,
) -> None:
    """Package W's criterion, on a chain that really produced something to publish.

    `_generation_already_current` is the gate #271 added: every thirty seconds the
    publisher was writing a whole new `serving.duckdb`, fsyncing it and moving
    `current.json`, because two of its six sources changed their generation id on every
    iteration and the read model carries the observation instant besides. The gate has to
    sit before the build, since a generation's identity includes the hash of a file that
    has not been written yet.

    So the second pass here runs over sources that have not moved, and the assertion is
    that the directory is byte-for-byte what it was.
    """

    route = active_notifier_chain
    publish_minute_batch(route)
    publish_candidates(route)
    drive_the_chain(route, credentials_root_active, hops=[])

    first = serving_generations(route)
    assert len(first) == 1, first
    pointer_before = serving_current(route)
    from tests.runtime_readonly_sandbox import tree_state

    serving_root = setting_of(route, "serving.publisher.v1", "serving_root")
    before = tree_state(serving_root)

    serving = instance_of(route, SERVING_ROLE)[0]
    run = run_at(route, SERVING_ROLE, instance=serving, now=SERVING_NOW + timedelta(seconds=31))

    assert run.entered, run
    assert run.last_error is None, run.last_error
    assert serving_generations(route) == first, "serving cut a second generation"
    assert serving_current(route) == pointer_before
    assert tree_state(serving_root) == before, "serving rewrote its own directory"
