"""Web can only call the concrete private paper admission contract."""

from typing import Protocol, runtime_checkable
from uuid import UUID

from rquant.paper_operator_commands import PaperPortfolioCommand, PaperOperatorConfirmation, SetPaperAccountPaused
from rquant.paper_portfolio_models import PaperPortfolioStateIdentity
from rquant.paper_portfolio_admission import PaperPortfolioAdmissionResult, PaperPortfolioZip


@runtime_checkable
class PaperPortfolioGateway(Protocol):
    def run_available(self, *, authenticated_actor_id: str) -> bool: ...
    def lookup(self, request: PaperPortfolioCommand, *, authenticated_actor_id: str) -> PaperPortfolioAdmissionResult | None: ...
    def resume(self, request: PaperPortfolioCommand, *, authenticated_actor_id: str) -> PaperPortfolioAdmissionResult: ...
    def prepare(self, request: SetPaperAccountPaused, *, authenticated_actor_id: str, verified_metadata_identity: PaperPortfolioStateIdentity) -> PaperOperatorConfirmation: ...
    def submit(self, request: PaperPortfolioCommand, *, authenticated_actor_id: str, verified_metadata_identity: PaperPortfolioStateIdentity, confirmation_id: str | None = None) -> PaperPortfolioAdmissionResult: ...
    def download(self, *, account_id: str, job_id: UUID, authenticated_actor_id: str) -> PaperPortfolioZip: ...
